### ISSUE TITLE
Permissions for application sets inside project roles are not applied

### ISSUE THREAD

**Issue by omallo** [argoproj/argo-cd#11811]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Permissions for application sets defined inside the project roles are not applied.

**To Reproduce**

Apply the following project using `kubectl`:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: alpha-dev
  namespace: argo-cd
spec:
  destinations:
    - server: https://kubernetes.default.svc
      namespace: alpha-dev
  sourceRepos:
    - "*"
  roles:
    - name: admin
      policies:
        - p, proj:alpha-dev:admin, projects, *, alpha-dev, allow
        - p, proj:alpha-dev:admin, applications, *, alpha-dev/*, allow
        - p, proj:alpha-dev:admin, applicationsets, *, alpha-dev/*, allow
        - p, proj:alpha-dev:admin, exec, *, alpha-dev/*, allow
        - p, proj:alpha-dev:admin, repositories, *, alpha-dev/*, allow
      groups:
        - alpha:dev:admin
```

Then login as a user with the above role (change it as appropriate) and check whether the application set permissions are granted:
```shell
argocd account can-i create applicationsets "alpha-dev/*"
no
```

Trying to create an application set also fails:
```shell
argocd appset create my-appset.yaml
FATA[0000] rpc error: code = Unknown desc = error checking create permissions for ApplicationSets dev : rpc error: code = PermissionDenied desc = permission denied: applicationsets, create, alpha-dev/dev, sub: 771f9161-fa28-4093-9d0a-59684ea9c62b, iat: 2022-12-22T09:25:19Z
```

**Expected behavior**

Permissions for application sets defined inside project roles must be applied.

Notes:
* If the same permission policy is added to the global `policy.csv`, the permissions on application sets are applied correctly.
* The permission policies in the project roles for all resources other than application sets are applied correctly.

So there seems to be some issue specifically with application set permissions inside project roles.

**Screenshots**

n/a

**Version**

```shell
argocd: v2.5.5+fc3eaec.dirty
  BuildDate: 2022-12-16T18:30:45Z
  GitCommit: fc3eaec6f498ddbe49a5fa9d215a219191fba02f
  GitTreeState: dirty
  GoVersion: go1.19.4
  Compiler: gc
  Platform: darwin/arm64

argocd-server: v2.5.5+fc3eaec
  BuildDate: 2022-12-16T16:10:27Z
  GitCommit: fc3eaec6f498ddbe49a5fa9d215a219191fba02f
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/arm64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
```

**Logs**

n/a

**Comment by neurodrone** [comment]
Is there any update on this? We are hitting the same issue on v2.5.7.

**Comment by Deofex** [comment]
When you go to the project role via the argoCD console and you try to edit it from there (change the description for example) and save tit, does that work? The added role is validated when you do it like this, more than once I found errors in my code, when I tried to edit the role via the console afterwards.

If you can edit the role via the argoCD console, can you also verify that the group you have edit in your code is visible in the users "user info". Like this: 
![image](https://user-images.githubusercontent.com/28751252/225885103-2cbec7d2-3320-45ca-8fce-5051dfad0e02.png)

**Comment by iamraj007** [comment]
interested in knowing the cause and fix.
If we add/update policies in **AppProject** for a user created in **argocd-cm**, will the permission given in AppProject be respected/work.
It did not work for me may be wrong approach, SO still looking for update here 
Thx

**Comment by msobkowiak-olx** [comment]
Probably related to: https://github.com/argoproj/argo-cd/issues/16441

**Comment by log1cb0mb** [comment]
@msobkowiak-olx Tried the fix (2.14.8 and also 2.4.10) versions and permission issue still seems to be there. In my case, i am using Azure AD object ID as group:

```
    - name: pleasework
      description: Role for bleh Project
      policies:
        - p, proj:bleh:pleasework, applicationsets, *, bleh/*, allow
      groups:
        - "000000-11111-4111a1c7-1919191919"
```

Meanwhile if the role is defined for same group under global rbac (rbac-cm), it seems to work as expected. getting permission when doing the same thing under AppProject. The policy seems to be fine from the looks of it and UI shows it as it should.

By any chance, this is by design that role and group must come from global rbac and by admin for appsets? Then again if this was the case, why would we even have an option for it to be under project? Or it is so that only role must come from global rbac while policy can be under AppProject?

**Comment by log1cb0mb** [comment]
This has been resolved with https://github.com/argoproj/argo-cd/pull/23252

**Comment by santosr2** [comment]
It appears that the latest version is still experiencing this issue. To resolve it, I need to set `proj:<project>:<role>` in the global RBAC. This is unusual, as the documentation states that the group match is generated at runtime.

> [Argo CD will use the policies defined in the AppProject roles while authorizing users actions. To determine which role a given users is associated with, it will dynamically create groups based on the role name in runtime.](https://argo-cd.readthedocs.io/en/stable/user-guide/projects/#project-roles)

Using the example provided in the question, it would look something like this:

#### AppProject:
```yaml
...
  roles:
    - name: admin
      policies:
        - p, proj:alpha-dev:admin, projects, *, alpha-dev, allow
        - p, proj:alpha-dev:admin, applications, *, alpha-dev/*, allow
        - p, proj:alpha-dev:admin, applicationsets, *, alpha-dev/*, allow
        - p, proj:alpha-dev:admin, exec, *, alpha-dev/*, allow
        - p, proj:alpha-dev:admin, repositories, *, alpha-dev/*, allow
      groups:
        - alpha:dev:admin
```

#### Global RBAC
```yaml
rbac:
    policy.csv: |
      g, alpha:dev:admin, proj:alpha-dev:admin
```

> [!NOTE]
> If your AppProject has multiple groups, list each in the global RBAC.
