### ISSUE TITLE
values.yaml updates in git for a multi source application are not synced

### ISSUE THREAD

**Issue by lsoica** [argoproj/argo-cd#12527]
**Describe the bug**

- Apply a multi source app with helm + values from git.
- Due to this bug https://github.com/argoproj/argo-cd/issues/12526: you have to manually transition the app to a healthy state by "Refresh"-ing the app
- Do a change in the values.yaml in GIT
- The change is not picked up

**To Reproduce**

Apply a manifest like:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multisourceapplication
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true        
  destination:
    server: https://kubernetes.default.svc
    namespace: multisourceapp
  sources:
  - repoURL: 'https://stefanprodan.github.io/podinfo/'
    chart: podinfo
    targetRevision: "5.1.0"
    helm:
      valueFiles:
      - $environment/configuration/applicationservices/podinfo-values.yaml
  - repoURL: 'https://<redacted git server and repo name>.git'
    targetRevision: HEAD
    ref: environment
```
Refresh the app in order to move to "Healthy" and "Synced".
Update the podinfo-values.yaml from:
```
replicaCount: 1
```
to
```
replicaCount: 2
```
and commit&push the changes.

Then check the podinfo deployment replicas and observe it's still 1 and does not change to 2.

**Expected behavior**
podinfo deployment should be scaled to 2 replicas.

**Version**

```
v2.6.2+6e02f8b
```

**Comment by frittenlab** [comment]
I am seeing the same behavior here too. Except my app is also stuck in Progressing the Health Check to. If i deploy the same application from a mono repo with an umbrella chart including the values.yaml. Everything works fine.

**Comment by kkamaldinov** [comment]
duplicate
https://github.com/argoproj/argo-cd/issues/12379

**Comment by lsoica** [comment]
Fixed by https://github.com/argoproj/argo-cd/pull/12576

**Comment by gilles-gosuin** [comment]
I just upgraded to v2.6.3+e05298b, this issue is still present. Should I open a new issue or will you re-open this one?
