### ISSUE TITLE
Web login via dex works, cli login returns "Invalid client credentials.

### ISSUE THREAD

**Issue by empath** [argoproj/argo-cd#1266]
I get the following error when trying to login with sso:

Response: {"error":"invalid_client","error_description":"Invalid client credentials."}

```argocd login <argo-address> --sso
Opening browser for authentication
Performing authorization_code flow login: https://<dex-address>/auth?access_type=offline&client_id=dex-secret-argocd&redirect_uri=http%3A%2F%2Flocalhost%3A8085%2Fauth%2Fcallback&response_type=code&scope=openid+profile+email+groups+offline_access&state=JLHDPFqavX
FATA[0009] oauth2: cannot fetch token: 401 Unauthorized
Response: {"error":"invalid_client","error_description":"Invalid client credentials."}```

**Comment by jessesuen** [comment]
@empath can you provide additional details of your SSO configuration?

1. Are you configuring using `dex.config` or `oidc.config`?

2. Which dex connector are you using?

3. Can you share redacted version of dex config?

**Comment by empath** [comment]
oidc config

oidc.config: |
    name: dex
    issuer: <dex-address>
    clientID: dex-secret-argocd
    clientSecret: $sso.client_secret

I'm using an ldap connector..

dex config 
- id: dex-secret-argocd
      redirectURIs:
      - "<argo callback address>"
      - "http://localhost:8085/auth/callback"
      name: dex-argocd
      secret: ...

Keep in mind, i can log into argo with dex via the web ui just fine -- just the cli isn't working.

**Comment by empath** [comment]
Okay so the problem seems to be that the argo cli needs to have public: true in the staticclient config in dex.  I changed the dex config to be public and deleted the sexret, and the cli works, but then the web login no longer works.

so i think I need soemthing like:

```
- id: dex-secret-argocd-web
      redirectURIs:
      - <argo callback address>
      name: dex-argocd-web
      secret: ...
- id: dex-secret-argocd-cli
      redirectURIs:
     - "http://localhost:8085/auth/callback"
      name: dex-argocd
      public: true
```

But i don't know the config i need in the argo config to make the cli use a different oidc id than the web front end uses..

**Comment by jessesuen** [comment]
From slack:
> (Based on looking at the code). Seems like it would be a relatively easy fix to add an cliclientid to the oidc.config though.

I understand the problem now. yes you are right. i think to support self hosted dex, we’ll need to provide a new field in the oidc.client config to give self provided client id. then the cli code should change:
```golang
if set.DexConfig != nil && len(set.DexConfig.Connectors) > 0 {
        clientID = common.ArgoCDCLIClientAppID
        issuerURL = fmt.Sprintf("%s%s", set.URL, common.DexAPIEndpoint)
} else if set.OIDCConfig != nil && set.OIDCConfig.Issuer != "" {
        clientID = set.OIDCConfig.ClientID
        issuerURL = set.OIDCConfig.Issuer
```
to use that if present

**Comment by jessesuen** [comment]
I have an **_untested_** set of changes:

https://github.com/argoproj/argo-cd/pull/1307

jessesuen/argocd:v0.12.0-dex-cli-fix

[argocd-darwin-amd64.zip](https://github.com/argoproj/argo-cd/files/2993446/argocd-darwin-amd64.zip)

**Comment by jessesuen** [comment]
Should be fixed with: https://github.com/argoproj/argo-cd/pull/1307. Verified that the new `cliClientID` config map setting is exposed in settings API, which the CLI will use when connecting to OAuth2 provider.

**Comment by zeph** [comment]
careful guys, as this still fails on plain oicd integration (with no dex involvement) setups https://github.com/argoproj/argo-cd/issues/2932
