### ISSUE TITLE
Apps in Any Namespace: Warnings thrown when viewing application in UI

### ISSUE THREAD

**Issue by patrickbardo** [argoproj/argo-cd#13694]
**Describe the bug**
When running ArgoCD with application-namespaces, if an application is created in another namespace, and then viewed in the UI, an error pops up as seen below in screenshots.

The links field fails to load, and checking the logs, it looks as if the server is looking for the application in the argocd namespace, even though it is in another namespace. 

`level=warning msg="application does not exist" application=xxx namespace=argocd`

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**To Reproduce**

- Run system with --application-namespaces=*
- Create application with `metadata.namespace` anything other than argocd (to match exactly, this was done tracking resources in a private repo)
- As admin role, open the application resource

**Expected behavior**

- The error should show, with links failing to load (no links need to be present in the definition).
- The server logs should include the logs pasted below.

**Screenshots**

![Screenshot 2023-05-23 at 08 47 53](https://github.com/argoproj/argo-cd/assets/76942752/f0df2043-e74b-4e53-9593-427a6ff7ace3)

**Version**

```shell
argocd: v2.7.2+cbee7e6.dirty
  BuildDate: 2023-05-12T15:33:14Z
  GitCommit: cbee7e6011407ed2d1066c482db74e97e0cc6bdb
  GitTreeState: dirty
  GoVersion: go1.20.4
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.7.1+5e54351.dirty
  BuildDate: 2023-05-02T16:35:40Z
  GitCommit: 5e543518dbdb5384fa61c938ce3e045b4c5be325
  GitTreeState: dirty
  GoVersion: go1.19.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.0.1 2023-03-14T01:32:48Z
  Helm Version: v3.11.2+g912ebc1
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**

```shell
level=warning msg="application does not exist" application=xxx namespace=argocd  
level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = permission denied" grpc.code=PermissionDenied grpc.method=ListLinks grpc.service=application.ApplicationService  span.kind=server system=grpc
```

**Comment by alexmt** [comment]
Thank you for reporting! Fixed by https://github.com/argoproj/argo-cd/pull/13664

**Comment by patrickbardo** [comment]
Ahh thanks so much!

**Comment by patrickbardo** [comment]
I just upgraded to latest with this bug fix, and I am still receiving the same error. It looks like the server is looking in the wrong namespace for the application resource.

**Comment by speedfl** [comment]
Hey. We have the same issue with latest version

**Comment by asohnlein-tsy** [comment]
This issue is also present for manifest editing not only on links field.

**Comment by speedfl** [comment]
For manifest editing this was fixed in [#13839](https://github.com/argoproj/argo-cd/pull/13839)

**Comment by speedfl** [comment]
@crenshaw-dev here the issue is a similar but needs bit more work as appNamepace is not even part of the query in the proto. I can take care of it today

**Comment by crenshaw-dev** [comment]
@speedfl is this completely resolved now that #13854 is merged?

**Comment by speedfl** [comment]
Yes all good on my side since upgrade to 2.7.7
