### ISSUE TITLE
failed to get version: %!w on v2.9.0-rc1

### ISSUE THREAD

**Issue by omegion** [argoproj/argo-cd#15686]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

- After upgrading to version `v2.9.0-rc1` CLI stopped working.

**To Reproduce**

- Upgrade CLI to `v2.9.0-rc1`
- Run any command against to the ArgoCD server.

**Expected behavior**

**Screenshots**

**Version**

```shell
❯ argocd version
argocd: v2.9.0-rc1+b3fabc2
  BuildDate: 2023-09-27T00:36:15Z
  GitCommit: b3fabc23cd613ecd7e213f55060ce007154d3fa8
  GitTreeState: clean
  GoVersion: go1.21.1
  Compiler: gc
  Platform: darwin/arm64
FATA[0005] all retries failed: failed to get version: %!w(<nil>)
```

**Logs**

```
❯ argocd app list
FATA[0005] all retries failed: failed to get version: %!w(<nil>)
```

**Comment by omegion** [comment]
@crenshaw-dev FYI 🙇🏼 

I am trying to use repo server name override with the latest version, but it seems not working :/

**Comment by crenshaw-dev** [comment]
I was not able to reproduce this. I was able to log in to our (2.8) server with the 2.9.0-rc1 CLI and then run `version`.

**Comment by omegion** [comment]
Interesting, is it possible that we have SSO enabled, but I try with `--core` 🤔

**Comment by omegion** [comment]
I tried to debug, and I've changed:
```
cli.SetLogLevel(log.DebugLevel.String())
log.SetLevel(log.DebugLevel)
```
on https://github.com/argoproj/argo-cd/blob/7317d6db33afd5f8c1108c5a95885590e9159ff4/cmd/argocd/commands/headless/headless.go#L173-L174

here are the logs:
```
❯ go run ./cmd app list
INFO[0000] Starting configmap/secret informers          
INFO[0000] Configmap/secret informer synced             
INFO[0000] invalidated cache for resource in namespace: argocd with the name: argocd-notifications-cm 
INFO[0000] invalidated cache for resource in namespace: argocd with the name: argocd-notifications-secret 
INFO[0000] argocd v99.99.99+unknown serving on port 58508 (url: , tls: false, namespace: argocd, sso: false) 
INFO[0000] Enabled application namespace patterns: argocd 
INFO[0000] 0x1400179c420 subscribed to settings updates 
INFO[0000] Starting rbac config informer                
INFO[0000] RBAC ConfigMap 'argocd-rbac-cm' added        
INFO[0000] received unary call /version.VersionService/Version  grpc.method=Version grpc.request.content= grpc.service=version.VersionService grpc.start_time="2023-09-27T19:46:57+02:00" span.kind=server system=grpc
INFO[0000] kustomize version --short                     dir= execID=67385
INFO[0000] Trace                                         args="[kustomize version --short]" dir= operation_name="exec kustomize" time_ms=0.028084
INFO[0000] helm version --client --short                 dir= execID=7ba4a
DEBU[0000] v3.11.3+g66a969e                              duration=111.966292ms execID=7ba4a
INFO[0000] Trace                                         args="[helm version --client --short]" dir= operation_name="exec helm" time_ms=112.18916700000001
INFO[0000] finished unary call with code OK              grpc.code=OK grpc.method=Version grpc.service=version.VersionService grpc.start_time="2023-09-27T19:46:57+02:00" grpc.time_ms=112.807 span.kind=server system=grpc
INFO[0000] received unary call /version.VersionService/Version  grpc.method=Version grpc.request.content= grpc.service=version.VersionService grpc.start_time="2023-09-27T19:46:57+02:00" span.kind=server system=grpc
INFO[0000] finished unary call with code OK              grpc.code=OK grpc.method=Version grpc.service=version.VersionService grpc.start_time="2023-09-27T19:46:57+02:00" grpc.time_ms=0.078 span.kind=server system=grpc
INFO[0001] received unary call /version.VersionService/Version  grpc.method=Version grpc.request.content= grpc.service=version.VersionService grpc.start_time="2023-09-27T19:46:58+02:00" span.kind=server system=grpc
INFO[0001] finished unary call with code OK              grpc.code=OK grpc.method=Version grpc.service=version.VersionService grpc.start_time="2023-09-27T19:46:58+02:00" grpc.time_ms=0.211 span.kind=server system=grpc
INFO[0001] received unary call /version.VersionService/Version  grpc.method=Version grpc.request.content= grpc.service=version.VersionService grpc.start_time="2023-09-27T19:46:58+02:00" span.kind=server system=grpc
INFO[0001] finished unary call with code OK              grpc.code=OK grpc.method=Version grpc.service=version.VersionService grpc.start_time="2023-09-27T19:46:58+02:00" grpc.time_ms=0.294 span.kind=server system=grpc
INFO[0002] received unary call /version.VersionService/Version  grpc.method=Version grpc.request.content= grpc.service=version.VersionService grpc.start_time="2023-09-27T19:46:59+02:00" span.kind=server system=grpc
INFO[0002] finished unary call with code OK              grpc.code=OK grpc.method=Version grpc.service=version.VersionService grpc.start_time="2023-09-27T19:46:59+02:00" grpc.time_ms=0.32 span.kind=server system=grpc
INFO[0002] received unary call /version.VersionService/Version  grpc.method=Version grpc.request.content= grpc.service=version.VersionService grpc.start_time="2023-09-27T19:46:59+02:00" span.kind=server system=grpc
INFO[0002] finished unary call with code OK              grpc.code=OK grpc.method=Version grpc.service=version.VersionService grpc.start_time="2023-09-27T19:46:59+02:00" grpc.time_ms=0.162 span.kind=server system=grpc
INFO[0003] received unary call /version.VersionService/Version  grpc.method=Version grpc.request.content= grpc.service=version.VersionService grpc.start_time="2023-09-27T19:47:00+02:00" span.kind=server system=grpc
INFO[0003] finished unary call with code OK              grpc.code=OK grpc.method=Version grpc.service=version.VersionService grpc.start_time="2023-09-27T19:47:00+02:00" grpc.time_ms=0.175 span.kind=server system=grpc
INFO[0003] received unary call /version.VersionService/Version  grpc.method=Version grpc.request.content= grpc.service=version.VersionService grpc.start_time="2023-09-27T19:47:00+02:00" span.kind=server system=grpc
INFO[0003] finished unary call with code OK              grpc.code=OK grpc.method=Version grpc.service=version.VersionService grpc.start_time="2023-09-27T19:47:00+02:00" grpc.time_ms=0.13 span.kind=server system=grpc
INFO[0004] received unary call /version.VersionService/Version  grpc.method=Version grpc.request.content= grpc.service=version.VersionService grpc.start_time="2023-09-27T19:47:01+02:00" span.kind=server system=grpc
INFO[0004] finished unary call with code OK              grpc.code=OK grpc.method=Version grpc.service=version.VersionService grpc.start_time="2023-09-27T19:47:01+02:00" grpc.time_ms=0.207 span.kind=server system=grpc
INFO[0004] received unary call /version.VersionService/Version  grpc.method=Version grpc.request.content= grpc.service=version.VersionService grpc.start_time="2023-09-27T19:47:01+02:00" span.kind=server system=grpc
INFO[0004] finished unary call with code OK              grpc.code=OK grpc.method=Version grpc.service=version.VersionService grpc.start_time="2023-09-27T19:47:01+02:00" grpc.time_ms=0.478 span.kind=server system=grpc
FATA[0005] all retries failed: failed to get version: %!w(<nil>) 
exit status 1
```

**Comment by omegion** [comment]
Hi @crenshaw-dev!

Any chance you tried with `--core`?

**Comment by blakepettersson** [comment]
Think this should be fixed with #15688

**Comment by omegion** [comment]
@blakepettersson The issue still persists with `v2.9.0-rc3` :(

**Comment by jacksgt** [comment]
The fix only landed in the `master` branch but was not backported to the [release-2.9](https://github.com/argoproj/argo-cd/tree/release-2.9) branch (yet?)

**Comment by blakepettersson** [comment]
Doesn't look like the cherry-pick command worked for me 😢, perhaps @gczuczy can help out to cherry-pick his change to the 2.9 branch?

**Comment by crenshaw-dev** [comment]
Picked! Will be in 2.9.0-rc4

**Comment by jacksgt** [comment]
Hi, I can confirm that it works with [2.9.0-rc4](https://github.com/argoproj/argo-cd/releases/tag/v2.9.0-rc4) - thanks for the fix and backporting it! :tada:
