### ISSUE TITLE
Inconsistency in redis key formation in ArgoCD 2.8.4 with compression enabled

### ISSUE THREAD

**Issue by purajit** [argoproj/argo-cd#15912]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

ArgoCD 2.8 enables Redis compression by default. However, after upgrading, I found I was unable to run commands like `argocd app diff/manifest`, since it would fail with 
```sh
ERRO[0031] finished unary call with code Unknown         error="error getting cached app managed resources: cache: key is missing" grpc.code=Unknown grpc.method=ManagedResources grpc.service=application.ApplicationService grpc.start_time="2023-10-11T10:30:18-07:00" grpc.time_ms=1554.185 span.kind=server system=grpc
``` 

Everything else runs without issue - syncing, UI browsing, etc.

**To reproduce**
Unsure what to mention here.

What I've tried that didn't help:
* verbose logging; but unfortunately nothing relevant shows up
* ensuring `REDIS_COMPRESSION` is `gzip` on all pods
* explicitly setting the `redis.compression` config to `gzip`
* explicitly setting `--redis-compress=gzip` as a server argument

What works:
* explicitly setting the `redis.compression` config to `none`

Current configuration:
* We use `--insecure --enable-gzip` (we handle TLS termination ourselves)
* We use the `public.ecr.aws/docker/library/haproxy,redis` repositories, with HA enabled.

**Expected behavior**

Everything should "just work", and key formation should be consistent.

**Version**

We're using the ArgoCD helm chart (v5.46.7).

```shell
# on server pod
> /usr/local/bin/argocd-server version
argocd-server: v2.8.4+c279299
  BuildDate: 2023-09-13T19:12:09Z
  GitCommit: c27929928104dc37b937764baf65f38b78930e59
  GitTreeState: clean
  GoVersion: go1.20.6
  Compiler: gc
  Platform: linux/amd64

# on local
> argocd version
argocd: v2.8.4+c279299
  BuildDate: 2023-09-13T19:43:37Z
  GitCommit: c27929928104dc37b937764baf65f38b78930e59
  GitTreeState: clean
  GoVersion: go1.20.7
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.8.4+c279299
  BuildDate: 2023-09-13T19:43:37Z
  GitCommit: c27929928104dc37b937764baf65f38b78930e59
  GitTreeState: clean
  GoVersion: go1.20.7
  Compiler: gc
  Platform: darwin/arm64
  Kustomize Version: could not get kustomize version: exec: "kustomize": executable file not found in $PATH
  Helm Version: v3.9.0+g7ceeda6
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```

**Logs**

I cleared out some cache keys, and then ran `redis-cli monitor | grep <application>` on the Redis pods:
```
1697046390.058300 [0 172.20.65.196:6379] "SET" "app|managed-resources|<application>|1.8.3.gz"
1697046390.060277 [0 172.20.65.196:6379] "SET" "app|managed-resources|<application>|1.8.3.gz"
1697046400.521017 [0 10.50.80.110:50238] "get" "app|managed-resources|<application>|1.8.3"
```

Note the lack of the suffix on the last one.

I could potentially add a ton of logging, build argo-cd and create an image, and deploy that to get more information, but I was hoping to see if anyone has dealt with this or knows what might be happening first. Looking at the code, I can't see why the key formation would ever be inconsistent.

Some relevant code paths:
* The only place where I can see some potential inconsistency with compression settings: https://github.com/argoproj/argo-cd/blob/v2.8.4/cmd/argocd/commands/headless/headless.go#L247
* Key formation logic: https://github.com/argoproj/argo-cd/blob/v2.8.4/util/cache/redis.go#L54
* Redis Get call: https://github.com/argoproj/argo-cd/blob/v2.8.4/util/cache/redis.go#L118

**Comment by crenshaw-dev** [comment]
Are you passing any flags on the `argocd app diff/manifests` command, or just the app name?

**Comment by ashinsabu3** [comment]
I have seen the same when I upgraded from argo 2.7.2 to argo 2.8.2, setting the `redis.compression` config to none seems to fix this.

**Comment by tberreis** [comment]
> I have seen the same when I upgraded from argo 2.7.2 to argo 2.8.2, setting the `redis.compression` config to none seems to fix this.

Don't know what's going wrong on my side but I can't get it work with
`redis.compression: none` set via [.Values.server.config](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/_helpers.tpl#L176) nor with
`--redis-compress none` set via [.Values.server.extraArgs](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-server/deployment.yaml#L76).

Worked well with 2.7.11, broke with 2.8.0 and is still broken in 2.9.0.

**Comment by cmontemuino** [comment]
Also confirmed that adding `redis.compression: none` in ConfigMap `argocd-cmd-params-cm` solves the issue. I'm also using ArgoCD v2.8.4.

**Comment by purajit** [comment]
> Are you passing any flags on the `argocd app diff/manifests` command, or just the app name?

Hey apologies, really need to figure out my GH notifications game.

Not passing in any other flags to the `argocd` commands (I don't have a cluster without compression available right now, but I believe I had this with and without `--local` as well)

**Comment by tooptoop4** [comment]
same issue in 2.10.3

**Comment by tooptoop4** [comment]
any idea? @aborilov

**Comment by agaudreault** [comment]
Might be ralted to https://github.com/argoproj/argo-cd/issues/5068

**Comment by clayvan** [comment]
> same issue in 2.10.3. redis.compression: none as workaround solves

Just to be clear, is this actually a mitigation for everyone else? For me, setting this did not resolve it. My only mitigation right now is to restart the `argocd-application-controller-0` and the error goes away for a few days.

**Comment by purajit** [comment]
I'm fairly certain, after seeing another unrelated issue, that it's because of https://github.com/argoproj/argo-cd/blob/73fbcc9ce4df743f119dfe1606fc6bc27844fe7d/cmd/argocd/commands/headless/headless.go#L311

**Comment by andrii-korotkov-verkada** [comment]
ArgoCD versions 2.10 and below have reached EOL. Can you upgrade and let us know if the issue is still present, please?

**Comment by purajit** [comment]
> ArgoCD versions 2.10 and below have reached EOL. Can you upgrade and let us know if the issue is still present, please?

I'm running 2.12, but haven't tried re-enabling compression. Let me try and get back to you

**Comment by purajit** [comment]
Look like the issue is resolved!

**Comment by pavelpikatamcs** [comment]
Nope, this is still failing with compression set to either `gzip` or `none`. ArgoCD version 2.13.2, upgraded from 2.11.0.
Rolling back to 2.11.0 fixes the issue, everything else mentioned in this thread doesn't help me.

/reopen

**Comment by tylermichael** [comment]
I'm on the latest ArgoCD version, and applying https://github.com/argoproj/argo-cd/issues/15912#issuecomment-1835823512 and restarting the argocd-application-controller with `kubectl -n argocd rollout restart statefulset argocd-application-controller` fixes the problem for me.

I landed at this issue from https://github.com/argoproj/argo-cd/issues/15077#issuecomment-1820985679 where they pointed to this fixing the problem for them as well.

A comment from the code mentioned above also explicitly calls out `core` auth mode.
https://github.com/argoproj/argo-cd/blob/73fbcc9ce4df743f119dfe1606fc6bc27844fe7d/cmd/argocd/commands/headless/headless.go#L309-L311

[Here](https://github.com/argoproj/argo-cd/blob/73fbcc9ce4df743f119dfe1606fc6bc27844fe7d/cmd/argocd/commands/headless/headless.go#L260) where the compression mode is used, it appears to be creating a "forwarded redis cache client" that I guess is pointing to the redis that ArgoCD uses? So, if you don't have the redis compression mode set to 'none' in your ArgoCD instance, which is what this is hardcoded to here, it fails.

**Comment by nitishfy** [comment]
Closing this in favour of https://github.com/argoproj/argo-cd/pull/21786

**Comment by qixiaobo** [comment]
The same problem meet!

![Image](https://github.com/user-attachments/assets/ff76cd10-755d-49c3-95b3-2e5454fb4bd4)
after add
redis.compression:none
This error disappears

**Comment by qixiaobo** [comment]
> [@qixiaobo](https://github.com/qixiaobo) in what version of Argo CD?

2.12 
To be honest,I think this is about the plugin breaking change.
https://github.com/argoproj/argo-cd/issues/17951 
I use the monorepo ,recently we upgrade the argocd to version 2.12, we finally find that the  error getting cached app managed resources: cache: key is missing

**Comment by qixiaobo** [comment]
I think this is the reason https://github.com/argoproj/argo-cd/issues/17951

**Comment by nitishfy** [comment]
are you using the `--core` flag?

**Comment by nitishfy** [comment]
Btw, we never cherry-picked that fix in 2.12. The cherry-picking is in 2.13 and 2.14.

**Comment by qixiaobo** [comment]
> Btw, we never cherry-picked that fix in 2.12. The cherry-picking is in 2.13 and 2.14.

I will try 2.14

**Comment by dodwmd** [comment]
My workaround for this is to delete the pvc's of the redis pods before syncing. I believe the problem is due to schema changes in redis. As it's just used for cache it can be safely removed between upgrades. Removing the pvc's will release once the pods terminate, which will give you new pods with new disks, the problem is you'll also need to manually terminate all the pods for a new cluster to form. Can keep compression on.

**Comment by younsl** [comment]
Setting redis.compression: none in the configuration does not resolve this issue in ArgoCD 2.13.4. The only temporary workaround currently is to restart the argocd-application-controller. The symptom is too critical - the UI frequently fails to load application data.

Is there any real fix or improvement planned for ArgoCD for this issue?
