### ISSUE TITLE
`argocd login --port-forward` fails with `cannot find pod with selector: [app.kubernetes.io/name=]`

### ISSUE THREAD

**Issue by noam-codefresh** [argoproj/argo-cd#16266]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

when trying to create a new argocd context using `port-forward`, the login commands fails with a new error. it worked fine in `v2.8.4`

**To Reproduce**
1. install a standard argo-cd instance to `argocd` namespace
2. extract the initial-admin-password from `argocd-initial-admin-secret` secret
3. run `argocd login --port-forward --port-forward-namespace argocd --username admin --password <pwd> --name whatever`

result:
```shell
FATA[0000] cannot find pod with selector: [app.kubernetes.io/name=] - use the --{component}-name flag in this command or set the environmental variable (Refer to https://argo-cd.readthedocs.io/en/stable/user-guide/environment-variables), to change the Argo CD component name in the CLI
```

**Expected behavior**

a new argo-cd context is created, with the name of `whatever`

**Version**

```shell
argocd: v2.9.0+9cf0c69.dirty
  BuildDate: 2023-11-06T15:07:24Z
  GitCommit: 9cf0c69bbe70393db40e5755e34715f30179ee09
  GitTreeState: dirty
  GoVersion: go1.21.3
  Compiler: gc
  Platform: darwin/arm64
```

**Comment by jzuijlek** [comment]
Similar issue when trying to start the dashboard on a Core install:

```
FATA[0000] cannot find pod with selector: [app.kubernetes.io/name=] - use the --{component}-name flag in this command or set the environmental variable (Refer to https://argo-cd.readthedocs.io/en/stable/user-guide/environment-variables), to change the Argo CD component name in the CLI
```

**Comment by noam-codefresh** [comment]
@jzuijlek - i tried debugging the `admin dashboard` command, to see if the case is similar to what i fixed for `login`. i couldn't reproduce the same error message, since i am getting
```shell
time="2023-11-09T15:36:26+02:00" level=fatal msg="error retrieving argocd-cm: configmap \"argocd-cm\" not found"
```

seems like it tries to look for `argocd-cm` in the `default` namespace, and it ignores the one i supply using the `-n <namespace>` flag. which is probably a different issue that needs to be resolved as well.

**Comment by yasharne** [comment]
I had the same issue, updating argo and cli to 2.9.1 didn't fix the issue, I had to spin up an ubuntu pod next the the argocd deployment and install the argocd cli there and do the configuration

**Comment by kuisathaverat** [comment]
The issue is still in 2.9.2

```
>kubectl config set-context --current --namespace argocd 
>argocd admin dashboard
FATA[0001] cannot find pod with selector: [app.kubernetes.io/name=] - use the --{component}-name flag in this command or set the environmental variable (Refer to https://argo-cd.readthedocs.io/en/stable/user-guide/environment-variables), to change the Argo CD component name in the CLI 
```

Revert to 2.8.7 resolves the issue.
```
argocd admin dashboard
```

**Comment by noam-codefresh** [comment]
yeah, i keep looking at `release-2.9` branch, and this issue was still not cherry-picked to it. i am not sure what to do about it.

**Comment by thesuperzapper** [comment]
@crenshaw-dev can we please cherry-pick this and cut a new 2.9.X asap, because this is breaking existing argocd CLI scripts.

**Comment by edi-bice** [comment]
@thesuperzapper that did the trick, now able to run deployKF sync_argocd_apps.sh

**Comment by thesuperzapper** [comment]
@alexmt @crenshaw-dev @todaywasawesome any chance we can cut a `2.9.4` version of the CLI which does not have this issue?

Because it's kind of breaking the sync script for deployKF (https://github.com/deployKF/deployKF/issues/70).

**Comment by noam-codefresh** [comment]
`release-2.10` branch was just created off `master`, with `12.10.0-rc1` tag released. so at least it's there, and will be in the next minor release.
but is there any chance it reaches `2.9`?
