### ISSUE TITLE
ExternalSecret Resource not getting deleted due to foregroundDeletion finalizer 

### ISSUE THREAD

**Issue by manali14** [argoproj/argo-cd#16925]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We have an external secret associated with an application. As soon as we click on sync, the secret gets deleted and externalSecret goes to a pendingDeletion state.

We are able to successfully sync the App by force deleting the external secret.

Also, though foreground deletion through argocd is stuck in PendingDeletion state, if we delete it manually using kubectl command through jumphost, it gets deleted without adding --force.

**To Reproduce**

Create an application with below manifest:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: <>
  namespace: argocd
spec:
  destination:
    name: '<>'
    namespace: dev
  project: <>
  source:
    helm:
      passCredentials: true
      releaseName: <>
      valueFiles:
        - values.yaml
        - values_dev.yaml
    path: <>
    repoURL: '<>'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

The application contains below k8s resources:

1. configMap
2. svc
3. pods
4. hpa
5. deployment
6. job
7. externalSecret (reading secrets from AWS Secrets Manager)
8. ingress
9. role
10. rolebinding

Post auto-sync/manually syncing the app, the secret deletes while the corresponding secret goes to a pendingDeletion state. It has to be manually deleted through jumphost/force deleted through argocd to get the deployment done.

**Expected behavior**

The application should recreate the external secret and sync successfully.

**Screenshots**

<img width="1226" alt="Screenshot 2024-01-19 at 3 25 15 PM" src="https://github.com/argoproj/argo-cd/assets/6524146/96ae07d9-d2b5-4f49-a59a-c3a38ef19c71">
<img width="1136" alt="Screenshot 2024-01-19 at 3 25 25 PM" src="https://github.com/argoproj/argo-cd/assets/6524146/af3acd4d-092f-47bd-b684-7730e0f3bad3">

**Version**

```shell
argocd: v2.8.2+dbdfc71
  BuildDate: 2023-08-24T20:37:23Z
  GitCommit: dbdfc712702ce2f781910a795d2e5385a4f5a0f9
  GitTreeState: clean
  GoVersion: go1.20.7
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.9.3+6eba5be
```

**Comment by chiragbhatia8** [comment]
Is anybody else also in community facing this issue?

**Comment by daftping** [comment]
This issue has been fixed in the External Secrets Controller https://github.com/external-secrets/external-secrets/pull/2718 and released in https://github.com/external-secrets/external-secrets/releases/tag/v0.9.5

**Comment by jaredhancock31** [comment]
Still seeing this on ArgoCD v2.9.6 and ESO 0.9.19.

Our ExternalSecret has `deletionPolicy: Retain`, but in cases where we still want to prune the `ExternalSecret` and leave the child secret behind - Argo gets hung up and the app stays out of sync until things are forced along manually.

**Comment by jaredhancock31** [comment]
@crenshaw-dev you're right. The issue is with ESO finalizers when using `creationPolicy: owner`. Ignore me!

**Comment by karlschriek** [comment]
@jaredhancock31 do you have some more context on how to fix this, or links to where it is discussed on ESO project?

**Comment by Aransh** [comment]
Started experiencing this as well (latest external-secrets version - 0.19.2), any clues on who the culprit is?
This seems to only happen with external secrets created via ArgoCD

**Comment by AlexisHW** [comment]
Same issue here with ESO 0.19.2.

**Comment by Aransh** [comment]
Just to reiterate on my comment, I don't believe it's related to ArgoCD, the behavior I found is that any externalSecret created before upgrading to 0.19 (from 0.15) has this issue.
If I force delete an externalSecret (by removing the finalizer) and then create it again, it works as expected and is removed properly next time

**Comment by AlexisHW** [comment]
I can confirm that after removing finalizers from old ExternalSecrets created in older ESO versions it gets deleted
`kubectl patch externalsecret <secret-name> -n <namespace> --type='json' -p='[{"op": "remove", "path": "/metadata/finalizers"}]'`

A newly created ExternalSecrets do not have this issue

**Comment by adam-elementor** [comment]
Also experiencing the same behavior exactly as posted here by the previous two comments
