### ISSUE TITLE
Service ingress-nginx-controller in progressing  state

### ISSUE THREAD

**Issue by fatsolko** [argoproj/argo-cd#17702]
**Describe the bug**

I add the `ingress-nginx` chart already installed in the k8s(187 days ago) to `argocd`, all resources are synchronized, but the service `ingress-nginx-controller` with type `LoadBalancer` is in a progressing state because: 
`waiting for healthy state of /Service/ingress-nginx-controller`.  

All the other apps with service type `ClusterIP` working normally. 

```
kubectl get svc -n ingress-nginx
NAME                                 TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)                      AGE
ingress-nginx-controller             LoadBalancer   10.233.18.180   115.122.6.8   80:31326/TCP,443:32306/TCP   187d
```

**To Reproduce**

Install chart ingress-nginx  version: 4.7.2 with service.type LoadBalancer and add it to argocd

**Expected behavior**

all resources healthy and synchronized

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/76652885/a10bd40f-123c-49a5-941a-a8ae8a181b30)

**Version**
argocd v2.8.4+c279299

**Comment by fatsolko** [comment]
> Here is the logic for whether a LoadBalancer Service is healthy: https://github.com/argoproj/gitops-engine/blob/5fd9f449e75774f6b2b7b1ff137c7759e075e385/pkg/health/health_service.go#L29
> 
> In the case where a Service is of type `LoadBalancer`, Argo CD will assume it is healthy iff the length of `.status.loadBalancer.ingress` is greater than 0.

Thank you for answer.
How can I fix this?

**Comment by jgwest** [comment]
@fatsolko My initial expectation is that this is not an Argo CD issue, but rather an issue with the configuration of the nginx ingress controller, and/or the K8s cluster.

You could try applying the nginx ingress controller without using Argo CD, and see if it works as expected there. FWIW I'm not aware of any other users that have reported issues with the Ingress health check.

**Comment by fatsolko** [comment]
> @fatsolko My initial expectation is that this is not an Argo CD issue, but rather an issue with the configuration of the nginx ingress controller, and/or the K8s cluster.
> 
> You could try applying the nginx ingress controller without using Argo CD, and see if it works as expected there. FWIW I'm not aware of any other users that have reported issues with the Ingress health check.

Nginx ingress controller worked without the Argo CD and works as expected, I just added it to the Argo CD later.

**Comment by jannfis** [comment]
This is documented as well [here](https://argo-cd.readthedocs.io/en/stable/operator-manual/health/#ingress).

Can you dump the complete YAML from that service, please?

Looking at the screenshot, the service is considered to be 6 months old. So it did exist in the cluster before you included it with an Argo CD application?

**Comment by fatsolko** [comment]
> So it did exist in the cluster before you included it with an Argo CD application?  

Yes  
> Can you dump the complete YAML from that service, please?  
```
kubectl get svc -o yaml ingress-nginx-controller -n ingress-nginx

apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"controller","app.kubernetes.io/instance":"ingress-nginx","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"ingress-nginx","app.kubernetes.io/part-of":"ingress-nginx","app.kubernetes.io/version":"1.8.2","helm.sh/chart":"ingress-nginx-4.7.2"},"name":"ingress-nginx-controller","namespace":"ingress-nginx"},"spec":{"externalIPs":["111.202.6.78"],"ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"appProtocol":"http","name":"http","port":80,"protocol":"TCP","targetPort":"http"},{"appProtocol":"https","name":"https","port":443,"protocol":"TCP","targetPort":"https"}],"selector":{"app.kubernetes.io/component":"controller","app.kubernetes.io/instance":"ingress-nginx","app.kubernetes.io/name":"ingress-nginx"},"type":"LoadBalancer"}}
    meta.helm.sh/release-name: ingress-nginx
    meta.helm.sh/release-namespace: ingress-nginx
  creationTimestamp: "2023-09-28T05:39:05Z"
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.8.2
    helm.sh/chart: ingress-nginx-4.7.2
    k8slens-edit-resource-version: v1
  name: ingress-nginx-controller
  namespace: ingress-nginx
  resourceVersion: "108066390"
  uid: 4a59b47a-cb13-4ce1-b32b-35858f3f9e4b
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.233.18.180
  clusterIPs:
  - 10.233.18.180
  externalIPs:
  - 111.202.6.78
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http
    name: http
    nodePort: 31126
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    nodePort: 32096
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
```

**Comment by Eijebong** [comment]
Seeing the same issue here, easy enough to reproduce, set `controller.hostNetwork` to true in the ingress-nginx helm chart. The service is declared as a load balancer but it looks like `status.loadBalancer` never gets filled out.

**Comment by hamishfor** [comment]
I'm also getting this issue. All services have their status.loadBalancer as an empty object.

**Comment by chetan94k** [comment]
Observed similar issue

**Comment by NikonNLG** [comment]
JFI: Fixed with adding MetalLB as a fake load balancer

**Comment by andrii-korotkov-verkada** [comment]
ArgoCD versions 2.10 and below have reached EOL. Can you upgrade and tell us if the issue is still present, please?

**Comment by Eijebong** [comment]
Updated to 2.13.0. The issue is still present.

![image](https://github.com/user-attachments/assets/a3b2844f-6bed-44aa-8656-4a471f0477f6)

**Comment by xmorose** [comment]
> ArgoCD versions 2.10 and below have reached EOL. Can you upgrade and tell us if the issue is still present, please?



> JFI: Fixed with adding MetalLB as a fake load balancer

Interesting solution, would you be able to provide me with the configs you used to achieve this? Would help out a ton!

**Comment by NikonNLG** [comment]
@xmorose I just add MetalLB chart and add unused subnet to it. Not sure how it will work with your cluster, so be careful.

metallb.yaml:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metallb
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: stage
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{.cluster}}-metallb'
    spec:
      project: system
      sources:
        - chart: metallb
          repoURL: https://charts.bitnami.com/bitnami
          targetRevision: 5.0.3
          helm:
            releaseName: metallb
        - repoURL: "git@git.host:devops/system-charts.git"
          path: metallb/{{.cluster}}
      destination:
        server: '{{.url}}'
        namespace: metallb
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
```
stage/metallb/crd.yaml
```
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lb-pool
  namespace: metallb
  annotations:
      argocd.argoproj.io/sync-wave: "1"
spec:
  addresses:
    - 192.168.21.0/24 # Unused subnet for local LB
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-adv
  namespace: metallb
  annotations:
      argocd.argoproj.io/sync-wave: "1"
```
