### ISSUE TITLE
Shows annotated tag's hash instead of commit's hash

### ISSUE THREAD

**Issue by aenshin-pp** [argoproj/argo-cd#20082]
After updating from `v2.4.28` to `v2.11.4` in the SYNC STATUS field we start to see hash of [annotated tag](https://rem.co/blog/2015/02/12/git-the-difference-between-lightweight-and-annotated-tags/) but not commit.

We have a tool which uses ArgoCD to make decisions during release. Tool is not healthy now since there is no commit hash anymore.

Expected behavior: always show commit hash.

**Comment by aenshin-pp** [comment]
Might be related to track down the issue:
https://github.com/argoproj/argo-cd/pull/4538

**Comment by aenshin-pp** [comment]
Here is how to reproduce the issue:
https://github.com/argoproj/argo-cd/issues/20083#issuecomment-2376706348

thanks to @anandf

**Comment by blakepettersson** [comment]
>@anandf @aenshin-pp I git bisected this, and it seems like the actual culprit is https://github.com/argoproj/argo-cd/pull/17874, which got introduced in 2.11-rc3.

**Comment by agaudreault** [comment]
@aenshin-pp can you update the description of the issue and add screenshots. I do not understand how this differs from #20083 and it is hard to know if it is resolve or not, as the reproduction steps are the one of the other resolved issues.

**Comment by aenshin-pp** [comment]
@agaudreault this is still unresolved. Reproduction steps are in this comment
https://github.com/argoproj/argo-cd/issues/20083#issuecomment-2376706348

It is located in another issue by mistake. Please read only the comment and ignore other comments and issue 20083 itself.

**Comment by jgwest** [comment]
I've updated the bug text with initial investigation results. 

We're also seeing a (likely) related behaviour, in that selfHealing is occurring in cases where it shouldn't when targeting an annotated tag. I've opened a new bug for this: https://github.com/argoproj/argo-cd/issues/21548

**Comment by blakepettersson** [comment]
This seems to have been fixed with #21771?

**Comment by ggogel** [comment]
@blakepettersson We have Argo CD `v3.0.16` and this issue still occurs. In our specific use case, this creates problems when using the promotion step  `argocd-update` in Kargo. Kargo resolves the annotated tag to the SHA of the actual commit, while Argo CD resolves it to the SHA of the annotated tag. This mismatch causes the promotion step  `argocd-update` to fail.

<img width="833" height="461" alt="Image" src="https://github.com/user-attachments/assets/b74f9485-b48d-4ffc-b11c-a5e5b8028784" />

<img width="904" height="113" alt="Image" src="https://github.com/user-attachments/assets/1cee1733-8400-4b8b-85e4-6e94488fba47" />

**Comment by blakepettersson** [comment]
@ggogel hmm, looking at this more closely I don't see any evidence that this is in the 3.0 branch (it _is_ in 2.13 and 2.14, as well in 3.1+ though).

**Comment by ggogel** [comment]
@blakepettersson thank you for the response. I can confirm that the issue is fixed in `v3.1.9`.

**Comment by blakepettersson** [comment]
#25241 is to cherry-pick this change for 3.0
