### ISSUE TITLE
Disruptive "PodDisruptionBudget has InsufficientPods" status

### ISSUE THREAD

**Issue by andrii-korotkov-verkada** [argoproj/argo-cd#20171]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Both desired and healthy available replicas can be equal, but the PDB can still be degraded with `PodDisruptionBudget has InsufficientPods`.

**To Reproduce**

Create a PDB which doesn't allow a single replica to go away, e.g. min availability 80% with 3 replicas.

**Expected behavior**

The PDB is healthy.

**Screenshots**

![Screenshot 2024-09-30 at 3 03 23 PM](https://github.com/user-attachments/assets/9964efb5-90ae-4a9a-baa5-d028462e84bc)
![Screenshot 2024-09-30 at 3 03 29 PM](https://github.com/user-attachments/assets/dc84ae7e-d022-4434-b6ac-721229d514f0)

**Version**

v2.13.0-rc2

**Logs**

**Comment by andrii-korotkov-verkada** [comment]
https://github.com/argoproj/argo-cd/pull/19826 might be related

**Comment by andrii-korotkov-verkada** [comment]
@afarbos, can you check whether your PR is related and fix the issue if it is, please?

**Comment by afarbos** [comment]
I don't understand the question, as much as I can see this seems to be expected behavior.
You should either adjust your PDB or fix the underlying issue. If not, the PDB wont be able to provide the desired value.

InsufficientPods is reported by kubernetes, see https://kubernetes.io/docs/reference/kubernetes-api/policy-resources/pod-disruption-budget-v1/#PodDisruptionBudgetStatus for more information overall on what PDB conditions means.

**Comment by andrii-korotkov-verkada** [comment]
> I don't understand the question, as much as I can see this seems to be expected behavior. You should either adjust your PDB or fix the underlying issue. If not, the PDB wont be able to provide the desired value.
> 
> InsufficientPods is reported by kubernetes, see https://kubernetes.io/docs/reference/kubernetes-api/policy-resources/pod-disruption-budget-v1/#PodDisruptionBudgetStatus for more information overall on what PDB conditions means.

Ah, `InsufficientPods: The number of pods are either at or below the number required by the PodDisruptionBudget. No disruptions are allowed and the status of the condition will be False.` So if it's exactly at the number, it'd still be false. I see.

**Comment by andrii-korotkov-verkada** [comment]
Seems like there's an edge case if the number of replicas can vary a lot, e.g. min is 3 and max is 30. Min at 3 requires PDB to be at most 66% to be healthy, but that seems small when we are at 30 replicas. I don't see a good solution to make it like 80% when at higher number of replicas, unless min replicas is increased to like 5. Do you have other ideas?

**Comment by afarbos** [comment]
I am not sure what min and max are referring to here but it does seems you could update the PDB maxUnavailable/minAvailable value in this case depending on pod count.

**Comment by akloss-cibo** [comment]
I've made a few comments on https://github.com/argoproj/argo-cd/pull/19826 over the last few weeks.  For us, it is not working very well:
* new software cannot be installed as the degraded PodDisruptionBudget is installed before the Deployment which will make it healthy.
* software that wants to use a PodDisruptionBudget to prevent any disruptions won't work (as described in this issue)
* PodDisruptionBudgets for pods provisioned by something without replicas (like Argo Workflows) don't work.

**Comment by andrii-korotkov-verkada** [comment]
Per discussion with Argo maintainers, it's better to just update PDBs to allow for disruptions.

**Comment by akloss-cibo** [comment]
I guess I'm confused.  I want the PDB to prevent disruptions, that's the point of having a PDB with no budget to allow a disruption.  If ArgoCD can't install a PDB (to a healthy status) than can prevent a disruption, then the PDB isn't helping me, right?

**Comment by akloss-cibo** [comment]
I endorse @sherifabdlnaby's observations.

**Comment by sherifabdlnaby** [comment]
Can we please re-open this one ? I think it's worth a discussion. Once we upgraded our ArgoCD Version many alerts fired because of "Degraded" state of the Argo App, even though from operational perspective everything is working as intended.

**Comment by andrii-korotkov-verkada** [comment]
Okay, I'll bring this up with Argo maintainers again. Maybe we should implement the check that doesn't fail if no disruptions are allowed.

**Comment by sherifabdlnaby** [comment]
One of the use-cases we also rely on PDB is for running Pre-sync jobs **reliably** for stuff like Migrations, etc.
We install PDB in an earlier Sync Wave, then expect the PDB to protect this pre-sync job from voluntarily disruptions. The PDB is designed to always be in "Disruption not allowed as long as there is a pre-sync job running".

We also install PDBs for CronJobs that run single replica jobs (`parallelism: 1`) 
... and again, the case where you have low replicas (e.g 3 replicas, one per AZ)...which is very common in Kubernetes in general.

**Comment by afarbos** [comment]
For all uses cases I have seen and documented online I could not fine such one described here. Could we include references, links or documentation? It would on many cases remove a lot of value for the argocd healthcheck on this resource and increase missuderstanding for many user.

Trying to abstract from specific here, it seems the main issues raised here is the fact some users can have specific uses case which are not the norm. If that's the case, could we consider creating a pattern upon those conditions, such as use metadata fields?
Idea:
```
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: foo
  namespace: bar
  annotations:
    argocd.argoproj.io/resource.health: disruptionAllowed
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: foo
```

**Comment by brainfair** [comment]
Hi, same story. We are using strict pdb in case of CI to prevent any disruption during tests. Now, all test deployments are going to fail because of the messed pdb status of the last 2.13 release.

**Comment by akloss-cibo** [comment]
This use case is documented [here](https://kubernetes.io/docs/tasks/run-application/configure-pdb/#think-about-how-your-application-reacts-to-disruptions):
> Possible Solution 2: Set PDB with maxUnavailable=0. Have an understanding (outside of Kubernetes) that the cluster operator needs to consult you before termination. When the cluster operator contacts you, prepare for downtime, and then delete the PDB to indicate readiness for disruption. Recreate afterwards.

**Comment by sherifabdlnaby** [comment]
> Trying to abstract from specific here, it seems the main issues raised here is the fact some users can have specific uses case which are not the norm.

What I am trying to say here that these use-cases are completely normal and it is referred to in Documentations too (as linked above). Also it's widely used inside companies based on my experience. It's used to protect all kind of Jobs, especially long running ones. So think of pre-sync jobs, Argo Workflows jobs, Cronjobs, etc. 

Relying on annotation is not the right approach IMO. There are many Charts that installs 3 replicas of a controller, and expect only 1 to be available (because they active-passive mode)... and it's NORMAL that during rollouts to be in a state where Disruptions are not Allowed.

**Comment by ajax-bychenok-y** [comment]
Well, for me PDB means that in some moment of time some specified percent of pods will be 100% (un)available. PDB with `minAvailable: 70%` and `3 pods` means that Kubernetes can't replace even any pod (because 1 pod is 33%) and it's not a problem, it's peculiarity. Anyway it's not by any means 'Degradated' status.

**Comment by Hronom** [comment]
We got this after upgrade to 2.13 release and I would say it's blocker.

Is there will be fix for this? Please release as soon as possible.

**Comment by andrii-korotkov-verkada** [comment]
@Hronom, yeah, the fix was merged and cherry-picked today, should get it in 2.13.1 when it's ready

**Comment by ArieLevs** [comment]
> @Hronom, yeah, the fix was merged and cherry-picked today, should get it in 2.13.1 when it's ready

thanks! this PDB issue caused us a lot of false `Degraded` alerts, hope 2.13.1 gets released soon

**Comment by agido-lehm** [comment]
Hi everyone, we still have the PDB issue with version 7.7.0, 7.7.1 and 7.7.2. Applications get the status -> Degraded. 
Is there a way to fix the problem here? Version 7.6.12 is the last version that runs without the problem.
BR

**Comment by andrii-korotkov-verkada** [comment]
2.13.1 wasn't released yet.

**Comment by agido-lehm** [comment]
the latest argo-cd version 7.7.3 just came in, but the problem is still there...

**Comment by brainfair** [comment]
Don't mess up the chart version and application version, chart 7.7.3 is still with application version 2.13.0
