### ISSUE TITLE
Hooks fail to apply in 2.14

### ISSUE THREAD

**Issue by sthomson-wyn** [argoproj/argo-cd#21804]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When there is a hook job (with a helm hook), the default behaviour according to https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/#hook-deletion-policies is `BeforeHookCreation` deletion

When we deploy a new version to argocd, the sync fails due to the old hook job not being deleted. This doesn't seem to happen if syncing the same version.

This did not occur on ArgoCD 2.13

**To Reproduce**

Job that currently exists at the time of update:

```
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: ****:batch/Job:****/****
    commitHash: ****
    helm.sh/hook: pre-upgrade,pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "200"
  creationTimestamp: "2025-02-06T10:48:14Z"
  generation: 1
  labels:
    app.kubernetes.io/app: ****
    app.kubernetes.io/component: ****
    app.kubernetes.io/instance: ****
    app.kubernetes.io/master-chart-hash: ****
    app.kubernetes.io/master-chart-version: 1.0.826
    app.kubernetes.io/name: ****
    app.kubernetes.io/part-of: ****
    app.kubernetes.io/version: 1.0.1352
    release: ****
    team: ****
  name: ****
  namespace: ****
  resourceVersion: "2068557027"
  uid: f323db91-f143-4731-a56c-1539db6742c6
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  selector:
    matchLabels:
      batch.kubernetes.io/controller-uid: f323db91-f143-4731-a56c-1539db6742c6
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/app: ****
        app.kubernetes.io/component: ****
        app.kubernetes.io/instance: ****
        app.kubernetes.io/master-chart-hash: ****
        app.kubernetes.io/master-chart-version: 1.0.826
        app.kubernetes.io/name: ****
        app.kubernetes.io/part-of: ****
        app.kubernetes.io/version: 1.0.1352
        batch.kubernetes.io/controller-uid: f323db91-f143-4731-a56c-1539db6742c6
        batch.kubernetes.io/job-name: ****
        cdk8s.io/metadata.addr: ****-c8799a9a
        controller-uid: f323db91-f143-4731-a56c-1539db6742c6
        job-name: ****
        release: ****
        team: ****
      name: ****
    spec:
      activeDeadlineSeconds: 300
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: Exists
            weight: 100
      containers:
      - env: ****
        envFrom:
        - configMapRef:
            name: infra-values
        image: ****:1.0.1352@****
        imagePullPolicy: Always
        name: startup
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: ****
          name: ****
          subPath: ****
        - mountPath: ****
          name: ****
          subPath: ****
      dnsPolicy: ClusterFirst
      priorityClassName: high-app-priority
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
        runAsGroup: 11000
        runAsNonRoot: true
        runAsUser: 11000
      setHostnameAsFQDN: false
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: cloud.google.com/gke-preemptible
        operator: Equal
        value: "true"
      volumes:
      - name: ****
        secret:
          defaultMode: 420
          secretName: ****
      - name: ****
        secret:
          defaultMode: 420
          items:
          - key: ****
            path: ****
          secretName: ****
status:
  completionTime: "2025-02-06T10:48:28Z"
  conditions:
  - lastProbeTime: "2025-02-06T10:48:28Z"
    lastTransitionTime: "2025-02-06T10:48:28Z"
    status: "True"
    type: Complete
  ready: 0
  startTime: "2025-02-06T10:48:14Z"
  succeeded: 1
  terminating: 0
  uncountedTerminatedPods: {}

```

Job that is attempting to be applied:

```
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    commitHash: ****
    helm.sh/hook: pre-upgrade,pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "200"
  labels:
    app.kubernetes.io/app: ****
    app.kubernetes.io/component: ****
    app.kubernetes.io/instance: ****
    app.kubernetes.io/master-chart-hash: ****
    app.kubernetes.io/master-chart-version: 1.0.826
    app.kubernetes.io/name: ****
    app.kubernetes.io/part-of: ****
    app.kubernetes.io/version: 1.0.1353
    release: ****
    team: ****
  name: ****
  namespace: ****
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/app: ****
        app.kubernetes.io/component: ****
        app.kubernetes.io/instance: ****
        app.kubernetes.io/master-chart-hash: ****
        app.kubernetes.io/master-chart-version: 1.0.826
        app.kubernetes.io/name: ****
        app.kubernetes.io/part-of: ****
        app.kubernetes.io/version: 1.0.1353
        cdk8s.io/metadata.addr: ****-c8799a9a
        release: ****
        team: ****
      name: ****
    spec:
      activeDeadlineSeconds: 300
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: Exists
              weight: 100
      containers:
        - env: ****
          envFrom:
            - configMapRef:
                name: infra-values
          image: ****:1.0.1353@****
          imagePullPolicy: Always
          name: startup
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
          volumeMounts:
            - mountPath: ****
              name: ****
              subPath: ****
            - subPath: ****
              name: ****
              mountPath: ****
      priorityClassName: high-app-priority
      restartPolicy: Never
      securityContext:
        fsGroup: 2000
        runAsGroup: 11000
        runAsNonRoot: true
        runAsUser: 11000
      setHostnameAsFQDN: false
      tolerations:
        - effect: NoSchedule
          key: cloud.google.com/gke-preemptible
          operator: Equal
          value: "true"
      volumes:
        - name: ****
          secret:
            secretName: ****
        - name: ****
          secret:
            items:
              - key: ****
                path: ****
            secretName: ****
```

**Screenshot**

![Image](https://github.com/user-attachments/assets/b486c33f-b5d7-4b5b-99a8-30cd70fec23e)

**Expected behavior**

The hook should be deleted before running again

**Version**

```shell
argocd: v2.11.3+3f344d5
  BuildDate: 2024-06-06T12:31:44Z
  GitCommit: 3f344d54a4e0bbbb4313e1c19cfe1e544b162598
  GitTreeState: clean
  GoVersion: go1.22.4
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.14.1+3345d05

```

**Logs**

```
Job.batch "***" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"***s", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:core.PodResourceClaim(nil)}}: field is immutable
```

**Comment by rouke-broersma** [comment]
This is a major regression and blocks most 3rd party helm charts from deploying properly

**Comment by maxbrunet** [comment]
Seeing the same with the `HookSucceeded` deletion policy, the sync gets stuck on "waiting for deletion of ... hooks", deletion never happens

**Comment by zswanson** [comment]
Any workaround other than staying on 2.13?

**Comment by pschichtel** [comment]
I reverted back to 2.13 after observing this issue on 2.14.3, but I still see the same behavior on 2.13.4 and even 2.13.0. I have several applications that get stuck waiting for hooks to be deleted that don't seem to ever go away.

**Comment by crenshaw-dev** [comment]
@pschichtel can you check whether the deletion timestamp gets set on the hook resource? If if does, check and see if some finalizer is blocking the deletion.

**Comment by crenshaw-dev** [comment]
I suspected the finalized, but i didn't think that logic got merged before 2.14... will investigate further.

**Comment by fire2** [comment]
We rolled back to 2.13 and don't have the issue anymore. We had since day 1 on 2.14 and on every deployment. Just my 2 cents.

**Comment by crenshaw-dev** [comment]
@pschichtel I wonder if manually clearing the finalizer in 2.13 would clear the issue. If the problem is a finalizer introduced by 2.14, that finalizer will stick around blocking deletions until something clears it.

**Comment by pschichtel** [comment]
@crenshaw-dev yep, that helped and makes total sense, if 2.13 doesn't handle these finalizers.

**Comment by crenshaw-dev** [comment]
Sweet. Yeah my theory is that 2.14 doesn't really handle them either, it just accidentally adds them because of a feature that won't actually be release until 3.0. Will look into it more tomorrow.

**Comment by pschichtel** [comment]
Does anyone have a quick way to found all objects in the cluster with this finalizer?

**Comment by rouke-broersma** [comment]
Looks like this is fixed in 2.14.4 for me

**Comment by sthomson-wyn** [comment]
I'm still seeing this on v2.14.4+3d901f2

**Comment by crenshaw-dev** [comment]
@sthomson-wyn if the finalizer is still present, you'll need th manually clear it.

**Comment by sthomson-wyn** [comment]
No finalizer is present on the hook

**Comment by crenshaw-dev** [comment]
@sthomson-wyn can you provide a publicly-runnable manifest that reproduces the issue?

**Comment by pschichtel** [comment]
For me it's working on 2.14.4. @sthomson-wyn argocd usually told me what objects it's awaiting deletion for. In my case it was jobs, configmaps, secrets, serviceaccounts, roles and rolebindings.

**Comment by zswanson** [comment]
> Confirmed, Argo CD 2.14.3 erroneously upgraded the gitops-engine library

@crenshaw-dev if its fixed thats great (thank you!), but for retrospective we saw the issue starting in 2.14.1

**Comment by crenshaw-dev** [comment]
Was the finalizer present?

**Comment by zswanson** [comment]
Not sure, not something I even would have thought to look for. We have a lot of apps using hooks for migrations etc so I had to roll back immediately, it was blocking our devs.

**Comment by crenshaw-dev** [comment]
So it's a different issue from the finalizer one, otherwise you'd have needed to manually clear the finalizer... have you tried upgrading again? If the issue is still present, there's more debugging to do.

**Comment by crenshaw-dev** [comment]
Closing since the consensus seems to be that this is fixed. Will reopen if @sthomson-wyn is able to add more details.

**Comment by henry-spanka** [comment]
Still seeing this on 2.14.6 with Kubernetes 1.31.

`Job.batch "orchestra-db-migrate" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:core.PodResourceClaim(nil)}}: field is immutable`

Deleting the Job (Hook) manually and syncing fixes this, but after it happens again.


Job is annotated with:

```yaml
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
```

This worked before in 2.13.X but broke after some update. Looks like the job is not deleted before syncing.

**Comment by pschichtel** [comment]
I can confirm what @henry-spanka wrote, I guess the helm deletion policy stuff now relies on the new functionality planned for argocd 3

**Comment by crenshaw-dev** [comment]
I'm not sure that `field is immutable` has anything to do with the 3.0 changes. Can you both consistently reproduce the failure in 2.14 but not in 2.13?

**Comment by henry-spanka** [comment]
I didn't revert back but it seems to be reproducible in 2.13 by some people.
The other change I made was change the resource tracking method to annotation.

Anyone else using resource tracking method `annotations`?

**Comment by sthomson-wyn** [comment]
> but it seems to be reproducible in 2.13 by some people.

Just curious where that's seen? 2.13 is still fine for me

Sorry I haven't provided a minimal repro... been a bit busy & upgrading to 2.14 blocks our devs

**Comment by henry-spanka** [comment]
> I reverted back to 2.13 after observing this issue on 2.14.3, but I still see the same behavior on 2.13.4 and even 2.13.0. I have several applications that get stuck waiting for hooks to be deleted that don't seem to ever go away.

@pschichtel reported it.

**Comment by pschichtel** [comment]
@henry-spanka my report, that 2.13 is also affected by this issue, was false, it was just the result of 2.14 adding finalizers that no controller will ever process and remove.

The "new" issue is that helm's deletion policies aren't respected, at least that is what I thought. I just started writing up an example hook resource to reproduce this issue derived from an internal helm chart, just to find out that there was a mistake in the internal Chart: the Job resource was missing the deletion policy.

After adding the deletion policy the issue is not reproducible for me and I haven't noticed this with other charts. It is strange that this didn't happen with 2.12 or 2.13, because this problem in the helm chart existed for a while (some resouces had the policy, but not all of them). So maybe 2.14 has actually fixed this inconsistency?

Strangely even though I have a hook-succeeded deletion policy, argocd still keeps the resource around.

**Comment by pschichtel** [comment]
This is a simple job derived from an internal helm chart, that I would expect to disappear after sync/helm upgrade:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: the-name
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: the-name
    spec:
      containers:
        - name: container
          image: docker.io/library/alpine:latest
          command: ["echo", "test"]
```

As I said, the before-hook-creation policy seems to work, but hook-succeeded seems to be ignored.

**Comment by sthomson-wyn** [comment]
https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/#hook-deletion-policies


fwiw before hook creation should be the default if none is specified

**Comment by sthomson-wyn** [comment]
Circling back to confirm that this is fixed for me in 3.0.2
