### ISSUE TITLE
Self-managed ArgoCD to 2.14.x unable to sync because redis-secret-init Job repeatedly runs and succeeds.

### ISSUE THREAD

**Issue by cResults** [argoproj/argo-cd#22167]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

I have an weird issue where redis-secret-init keeps looping.
I installed ArgoCD using the helm chart "7.8.2", app version "2.14.2+" including a values file.  redis-secret-init runs once succeeds and is later removed.  Everything is working as expected.

I then applied an app-of-apps that watches a dir with an ApplicationSet configured with platform services helm charts, including Argo CD.  After this, the redis-secret-init runs, succeeds, and runs again and again preventing Argo CD from completing a successful sync upon itself.

I uninstalled Argo CD and reinstalled with Helm Chart version "7.7.5" app version "2.13.1", however, [after reading this](https://github.com/argoproj/argo-cd/issues/19798) I don't know whether this broke in 2.14.x or if I just happened to win the race condition when installing "2.13.1".  [Another potentially related issue](https://github.com/argoproj/argo-helm/issues/2848).

This issue was reported [last week by Rune on Slack](https://cloud-native.slack.com/archives/C01TSERG0KZ/p1740492894407759).  The information below is from that post. It reflects what we are seeing:

The job, argocd-redis-secret-init itself exits "ok":
Checking for initial Redis password in secret argocd/argocd-redis at key auth.
Argo CD Redis secret state confirmed: secret name argocd-redis.
Password secret is configured properly.

`kubectl describe jobs argocd-redis-secret-init -n argocd` returns:
Events:
  Type    Reason            Age   From            Message
  ----    ------            ----  ----            -------
  Normal  SuccessfulCreate  3s    job-controller  Created pod: argocd-redis-secret-init-67n49
  Normal  Completed         0s    job-controller  Job completed

Complete output of above command:
Name:                        argocd-redis-secret-init
Namespace:                   argocd
Selector:                    batch.kubernetes.io/controller-uid=19b7598c-c830-4c0b-a5c4-c955f97e42e9
Labels:                      app.kubernetes.io/component=redis-secret-init
                             app.kubernetes.io/instance=argocd
                             app.kubernetes.io/managed-by=Helm
                             app.kubernetes.io/name=argocd-redis-secret-init
                             app.kubernetes.io/part-of=argocd
                             app.kubernetes.io/version=v2.14.2
                             argocd.argoproj.io/instance=argocd
                             helm.sh/chart=argo-cd-7.8.2
Annotations:                 argocd.argoproj.io/tracking-id: argocd:batch/Job:argocd/argocd-redis-secret-init
                             helm.sh/hook: pre-install,pre-upgrade
                             helm.sh/hook-delete-policy: before-hook-creation
Parallelism:                 1
Completions:                 1
Completion Mode:             NonIndexed
Suspend:                     false
Backoff Limit:               6
TTL Seconds After Finished:  60
Start Time:                  Tue, 25 Feb 2025 15:22:47 +0100
Completed At:                Tue, 25 Feb 2025 15:22:50 +0100
Duration:                    3s
Pods Statuses:               0 Active (0 Ready) / 1 Succeeded / 0 Failed
Pod Template:
  Labels:           app.kubernetes.io/component=redis-secret-init
                    app.kubernetes.io/instance=argocd
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=argocd-redis-secret-init
                    app.kubernetes.io/part-of=argocd
                    app.kubernetes.io/version=v2.14.2
                    batch.kubernetes.io/controller-uid=19b7598c-c830-4c0b-a5c4-c955f97e42e9
                    batch.kubernetes.io/job-name=argocd-redis-secret-init
                    controller-uid=19b7598c-c830-4c0b-a5c4-c955f97e42e9
                    helm.sh/chart=argo-cd-7.8.2
                    job-name=argocd-redis-secret-init
  Service Account:  argocd-redis-secret-init
  Containers:
   secret-init:
    Image:           quay.io/argoproj/argocd:v2.14.2
    Port:            <none>
    Host Port:       <none>
    SeccompProfile:  RuntimeDefault
    Command:
      argocd
      admin
      redis-initial-password
    Environment:   <none>
    Mounts:        <none>
  Volumes:         <none>
  Node-Selectors:  kubernetes.io/os=linux
  Tolerations:     <none>
Events:
  Type    Reason            Age   From            Message
  ----    ------            ----  ----            -------
  Normal  SuccessfulCreate  4s    job-controller  Created pod: argocd-redis-secret-init-4w4bk
  Normal  Completed         1s    job-controller  Job completed

**To Reproduce**

See description above

**Expected behavior**

Able to create an Application/ApplicationSet that configures Argo CD to enforce GitOps upon itself.

**Version**

helm chart "7.8.2", app version "2.14.2+" 

**Logs**

See above.

**Comment by rouke-broersma** [comment]
This has been fixed in 2.14.4 I think

**Comment by codrutpanea** [comment]
it still happens in 2.14.4

**Comment by ixxeL2097** [comment]
it still happens in 2.14.5 also. Endless loop. Output shows :
```console
Checking for initial Redis password in secret argocd/argocd-redis at key auth.
Argo CD Redis secret state confirmed: secret name argocd-redis.
Password secret is configured properly.
```

**Comment by rouke-broersma** [comment]
> it still happens in `v2.14.5` also (Helm chart version `7.8.10`). Endless loop. Output shows :
> ```console
> Checking for initial Redis password in secret argocd/argocd-redis at key auth.
> Argo CD Redis secret state confirmed: secret name argocd-redis.
> Password secret is configured properly.
> ```

I am not seeing this anymore, the job is removed correctly after the sync and does not restart. Have you tried manually deleting the whole redis sync job to make sure nothing of the previous bug is left over?

**Comment by fabhuebner** [comment]
> it still happens in `v2.14.5` also (Helm chart version `7.8.10`). Endless loop. Output shows :
> 
> Checking for initial Redis password in secret argocd/argocd-redis at key auth.
> Argo CD Redis secret state confirmed: secret name argocd-redis.
> Password secret is configured properly.

The same still me.
In my opinion, the reason is that the sync is not completed and the PreSync job hook (`helm.sh/hook: pre-install,pre-upgrade`) is constantly restarted. The job itself finishes successfully. It only stops when I stop the sync manually. I noticed it for the first time with version `2.14.2`

btw: I use `ServerSideApply=true` and manage Argo-CD by itself.

currently I use: Argo-CD `2.14.5` with Helm Chart `7.8.10` on GKE `1.32.1`

**Comment by fabhuebner** [comment]
I think it has something to do with the newly introduced parameter `controller.sync.timeout.seconds`. (see https://blog.argoproj.io/argo-cd-v2-14-release-candidate-57a664791e2a)
If I set this to e.g. “60” it works for me again.

**Comment by p4block** [comment]
I found a leftover Job with a broken finalizer that needed to be deleted in many clusters, one of them even refused to update it due to invalid yaml patch but I couldn't repro that. After fixing that, I encountered this error.
I fixed this by disabling serversideapply, syncing, and then enabling serverside apply again. It seems to sync now.

**Comment by fabhuebner** [comment]
It only works for me if I disable `ServerSideApply`. If I enable `ServerSideApply=true`, it has the same wrong behavior as before. But I need `ServerSideApply=true`

**Comment by p4block** [comment]
After an update to the chart to 7.8.11 from 7.8.10 (with no relevant changes) and without serverside apply, we are back to the related issue of argocd-secret-init syncing forever.

**Comment by maaft** [comment]
also experience this issue with latest 7.8.11 release

**Comment by cResults** [comment]
Are there any updates on this topic.  Waiting for this to be resolved before updating to latest.

**Comment by fabhuebner** [comment]
seems to be solved for me since Argo-CD `v2.14.8` with Helm Chart `v7.8.14`. Maybe someone else can confirm this.

**Comment by mhoyer** [comment]
It's not solved on our side, we just updated helm chart from `v7.8.2` to `v7.8.23` (`v2.14.2` → `v2.14.9`) and the issue shows up (for the first time). We have `ServerSideApply=true` set.

**Comment by brophyja** [comment]
Is there a reason the Redis pod doesn't just mount the password from the secret?  Why bother with the complexity (and trouble) of having an init container that needs to retrieve the secret from the Kubernetes API (e.g. https://github.com/argoproj/argo-cd/issues/18356)?

**Comment by rouke-broersma** [comment]
> Is there a reason the Redis pod doesn't just mount the password from the secret?  Why bother with the complexity (and trouble) of having an init container that needs to retrieve the secret from the Kubernetes API (e.g. https://github.com/argoproj/argo-cd/issues/18356)?

The Helm chart doesn't use a init container, it uses a job. The reason for the job is to generate the secret, not to retrieve the secret.

**Comment by raweber42** [comment]
Still happening on 3.0.0!

**Comment by mihstaub** [comment]
Still happening on 3.0.6

**Comment by sebbbastien** [comment]
Still happening on 3.1.0

**Comment by Anvill1** [comment]
If u are using istio try this (worked for me):
```yaml
redisSecretInit:
  enabled: true
  podAnnotations:
    sidecar.istio.io/inject: "false"
```

**Comment by crenshaw-dev** [comment]
I think this might be better addressed in https://github.com/argoproj/argo-helm ?

**Comment by ibauersachs** [comment]
@crenshaw-dev Well, there's an issue in argo-helm, but it was incorrectly closed: argoproj/argo-helm/issues/2887

**Comment by crenshaw-dev** [comment]
Asked @agaudreault to clarify why he closed it.

**Comment by mhrcm** [comment]
still happening on app version 3.1.2/chart 9.2.0

**Comment by agaudreault** [comment]
My bad! I closed the helm issue instead of the argo-cd one. Helm issue is re-opened.
