### ISSUE TITLE
308 infinite redirect

### ISSUE THREAD

**Issue by kotyara85** [argoproj/argo-cd#3274]
**Describe the bug**
argocd is in infinite 308 recdirect

**To Reproduce**
AWS setup - 
ELB (ssl) -> service port 80 argo-server -> loop redirect

```
spec:
  rules:
  - host: argocd
    http:
      paths:
      - backend:
          serviceName: argocd-server
          servicePort: 80
        path: /
  tls:
  - hosts:
    - argocd
```

Is there a way to disable redirect on argo side?

```
$ curl https://argocd
<a href="https://argocd/">Temporary Redirect</a>.
```

Thanks

**Comment by Addono** [comment]
Are you running the `argo-server` with the `--insecure` flag enabled? Correct me if I am wrong, but I assume that ELB handles TLS and forwards the traffic as plain HTTP to Argo. Without the `--insecure` flag Argo will try to upgrade this request to HTTPS, which causes this infinite redirect loop.

Ran into something similar Yesterday - although this was with using Traefik rather than ELB - and then it result in infinite 307s.

**Comment by kotyara85** [comment]
Yeah, that was the problem.
Fixed it a couple of days ago.
Thanks!

**Comment by blackliner** [comment]
So would it be possible to do the ssl offloading on the ELB, but still have HTTPS traffic between it and argocd-server?

**Comment by dscham** [comment]
I'm still getting a redirect to HTTPS after setting what @kshaharrajuan suggested....
