### ISSUE TITLE
Cascading delete should apply to all sub applications

### ISSUE THREAD

**Issue by jdfalk** [argoproj/argo-cd#3353]
Checklist:

* [X] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
We create a bootstrap application that contains all our applications. When you delete the bootstrap application with cascading delete on, it doesn't apply the cascading delete to objects created by sub applications. Leaving us with unmanaged resources.

**Diagram of layout**
```
└── bootstrap-application
    └── sub-application-1
        └── sub-application-2
```

**To Reproduce**
1. Create an kustomize based application that includes other applications (see above).
2. Delete bootstrap application with cascade=true.
3. Resources owned by sub-applicaiton-2 are not deleted but the application is.

**Expected behavior**

All resources should be deleted.

**Version**

```shell
argocd: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:43Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.5.0+d326dae
  BuildDate: 2020-04-03T09:32:29Z
  GitCommit: d326daef6203b2c205779afb9e240ca1c4f05552
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
  Kubectl Version: v1.14.0
```

**Comment by jannfis** [comment]
Hi @jdfalk, I think you need to set the finalizers in the manifests for your Application resources that are children in your app-of-apps patterns, as described in https://argoproj.github.io/argo-cd/user-guide/app_deletion/. 

The cascade delete does not set finalizers on resources (the child apps) of your application (the parent app).

/cc @alexmt - are the finalizers something we should propagate to Application resources?

**Comment by jdfalk** [comment]
Just verifying I am reading that right.
```
└── bootstrap-application <-- cascade delete here
    └── sub-application-1  <-- automatically sets finalizer here
        └── sub-application-2 <-- needs user to set finalizer here
              └─ sub-application-2-resource <-- finalizer will be set if the resource above it has the finalizer? or does it have to be applied to all resources?
```

**Comment by jannfis** [comment]
Ah so maybe I have understood the initial problem wrong. 

So when you delete the bootstrap application with `cascade=true`, the `sub-application-1` is deleted correctly and actually including its resources - which in this case is `sub-application-2`.

That would mean that the finalizer is actually set on `sub-application-1` (so, most likely inherited), but is not passed further down, in this case to `sub-application-2`.

I guess I need to reproduce that in a test environment to see what's going on.  I'm not sure which is the correct behaviour in this case.

**Comment by jdfalk** [comment]
This can probably be solved by getting rid of the app of app pattern and using the new applicationSet stuff once that's finalized. https://github.com/argoproj/argo-cd/issues/3403

**Comment by mksha** [comment]
@jdfalk @jannfis  i am still seeing this issue with application set

**Comment by mksha** [comment]
in my case , i even tried it for single app also
app -> create k8s resources
but on cascade delete , it does not delete the k8s resources.
can you guys pls take a look at it?

**Comment by mksha** [comment]
i am already specifying the 
finalizers:
    - resources-finalizer.argocd.argoproj.io

at argo application , so it should delete the k8s resource also on deletion.

**Comment by mksha** [comment]
https://github.com/argoproj-labs/applicationset/issues/230

**Comment by mksha** [comment]
@jannfis  its not issue with Application set as mentioned in above issue

**Comment by laloyalo** [comment]
Looks like this has been an ongoing issue for quite a while, I would suggest for you to provide a public repo reproducing the issue so that we could test in our own cluster, I have done App of Apps and AppSets, and after deleting (sometimes accidentally) the parent app, it deletes the children. Sorry to bother you with that, but it can help with:

1. For you to check again (sorry about that) the setup,
2. For the community to test out the behavior with a more concrete example.

Greetings!

**Comment by mksha** [comment]
will do, sure

**Comment by mksha** [comment]
Its working when we setup our argo config correctly or use default config. When i tried the same on my local cluster and argo cd instance all worked as expected. So it seems like its an issue with my argo cd instance that i have on diff cluster.

**Comment by mksha** [comment]
https://github.com/argoproj-labs/applicationset/issues/230

**Comment by peimanja** [comment]
So in my case I do not set the finalizer on the ApplicationSet itself or the template but generated applications have the finalizer on will delete the resources if the application is deleted.

ApplicationSet:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bootstrap-app1
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          bootstrap: "true"
  template:
    metadata:
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .
      labels:
        argocd-app: bootstrap-app1
        cluster: '{{name}}'
      name: bootstrap-app1-{{name}}
    spec:
      destination:
        name: '{{name}}'
        namespace: default
      project: default
      source:
        path: applications/bootstrap-app1
        plugin:
          env:
          - name: HELMFILE_ENV
            value: dev
          - name: NAMESPACE
            value: default
          - name: CLUSTER_NAME
            value: '{{name}}'
        repoURL: https://my-company.com/my-org/gitops-infra
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
  ````

Generated Application:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    argocd-app: bootstrap-app1
    cluster: infra-dev
  name: bootstrap-app1-infra-dev
spec:
  destination:
    name: infra-dev
    namespace: default
  project: default
  source:
    path: applications/bootstrap-app1
    plugin:
      env:
      - name: HELMFILE_ENV
        value: dev
      - name: NAMESPACE
        value: default
      - name: CLUSTER_NAME
        value: infra-dev
    repoURL: https://my-company.com/my-org/gitops-infra
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ```

I would like to be able to set the `finalizers` to `resources-finalizer.argocd.argoproj.io` only if I set it on the template. 

Basically I want to control if the resources should get deleted or not if the applicationset got deleted. right now if I delete the applicationset all argocd applications get deleted which is expected but there is no way to avoid deletion of the resources managed by these applications.  Any suggestions?
