### ISSUE TITLE
Helm ArgoCD does not take into account values cert-manager

### ISSUE THREAD

**Issue by isantospardo** [argoproj/argo-cd#4091]
**Describe the bug**:
Helm ArgoCD does not install cert-manager CRDs when specifying installCRDs: true

I have tried the following setup 
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-cert-manager
    server: https://kubernetes.default.svc
  project: default
  # tried workaround https://github.com/argoproj/argo-cd/issues/2239
  ignoreDifferences:
  - group: apiextensions.k8s.io
    jsonPointers:
    - /status
    kind: CustomResourceDefinition
    name: certificaterequests.cert-manager.io
  - group: apiextensions.k8s.io
    jsonPointers:
    - /status
    kind: CustomResourceDefinition
    name: certificates.cert-manager.io
  - group: apiextensions.k8s.io
    jsonPointers:
    - /status
    kind: CustomResourceDefinition
    name: challenges.cert-manager.io
  - group: apiextensions.k8s.io
    jsonPointers:
    - /status
    kind: CustomResourceDefinition
    name: challenges.acme.cert-manager.io
  - group: apiextensions.k8s.io
    jsonPointers:
    - /status
    kind: CustomResourceDefinition
    name: clusterissuers.cert-manager.io
  - group: apiextensions.k8s.io
    jsonPointers:
    - /status
    kind: CustomResourceDefinition
    name: issuers.cert-manager.io
  - group: apiextensions.k8s.io
    jsonPointers:
    - /status
    kind: CustomResourceDefinition
    name: orders.acme.cert-manager.io
  source:
    repoURL: {{ .Values.repoURL }}
    path: deploy/charts/cert-manager
    targetRevision: {{ .Values.targetRevision | quote }}
    helm:
      values: |
        ##
        ## Default values for openshift-cert-manager.
        ## This is a YAML-formatted file.
        ## Declare variables to be passed into your templates.
        ##
        global:
          leaderElection:
            # Override the namespace used to store the ConfigMap for leader election
            namespace: "openshift-cert-manager"
        installCRDs: true
        image:
          repository: "{{ .Values.controller.image }}"
          tag: "{{ .Values.controller.tag }}"
          pullPolicy: IfNotPresent

        # Override the namespace used to store DNS provider credentials etc. for ClusterIssuer
        # resources. This namespace will not be automatically created by the Helm chart.
        clusterResourceNamespace: "openshift-cert-manager"

        webhook:
          image:
            repository: "{{ .Values.webhook.image }}"
            tag: "{{ .Values.webhook.tag }}"
            pullPolicy: IfNotPresent

        cainjector:
          image:
            repository: "{{ .Values.cainjector.image }}"
            tag: "{{ .Values.cainjector.tag }}"
            pullPolicy: IfNotPresent
        ##
        ## End of additional cert-manager resource settings.
        ##
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```
Also I have tried without `ignoreDifferences` but it seems the CRDs are never installed. I also see the following error in the cainjector pod
```
cert-manager/controller-runtime/source "msg"="if kind is a CRD, it should be installed before calling Start" "error"="no matches for kind \"Certificate\" in version \"cert-manager.io/v1alpha2\""  "kind"={"Group":"cert-manager.io","Kind":"Certificate"}
```

In any case, a workaround is to install the CRDs manually by executing:
```
kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.16.1/cert-manager.crds.yaml
```

Also, installing the helm chart manually it success and install all the CRDs corrently
```
$ helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version v0.16.1 \
  --set installCRDs=true
```

**Expected behaviour**:
The CRDs should be automatically installed when adding `installCRDs: true` in the values file

**Environment details:**:
- cert-manager version: v.0.16.1
- ArgoCD version: v1.6.1+1
- Install method: ArgoCD + helm

I am not sure it is a bug in ArgoCD, but as far as I can see the helm install command works as expected, so I guess specifying the values in an ArgoCD application should make it work also. Any help is appreciated.

/kind bug

**Comment by isantospardo** [comment]
Working with cert-manager v0.15.2 and ArgoCD with latest version due to:
https://cert-manager.io/docs/installation/upgrading/upgrading-0.15-0.16/#helm and 
https://github.com/argoproj/argo-cd/issues/3998#issuecomment-665274896

**Comment by bobbywatson3** [comment]
Wait, is that a real solution? I can't get this to work with cert-manager v1.1.0. I don't want to have to pin cert-manager to v0.15.2 in order to make this work. cert-manager is currently on 1.1.0 with 1.2.0 coming soon.

**Comment by isantospardo** [comment]
We fixed it for 0.15, but it should be good if you are running 1.1.0, you can check [this](https://cert-manager.io/docs/installation/upgrading/upgrading-0.16-1.0/#helm) , if you accomplish the requirements.

**Comment by bobbywatson3** [comment]
I don't understand what "accomplish the requirements" means. That link says that helm and kubectl must be above a certain version. Helm and kubectl are installed as a part of argocd, and run from argocd. I am running the latest version of argocd. Does it not include Helm >= 3.3.1?

**Comment by jaredmcqueen** [comment]
I still can't get working with latest and greatest argocd.  Helm shows as version:
`version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}`
still will not install CRDs for cert-manager

**Comment by devtechmediatechai** [comment]
> I still can't get working with latest and greatest argocd. Helm shows as version: `version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}` still will not install CRDs for cert-manager

https://github.com/jetstack/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml#L42 
Can you try to set it to True ?

**Comment by qtheya** [comment]
> I still can't get working with latest and greatest argocd. Helm shows as version: `version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}` still will not install CRDs for cert-manager

https://github.com/jetstack/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml#L42
Try to set it to True.

**Comment by artem-zherdiev-ingio** [comment]
Hi, we still get this error.
Cert manager is v1.10.0
ArgoCD is v2.4.11+3d9e9f2
Helm is v3.8.1
values installCRDs: true

Chart.yml
dependencies:
  - name: cert-manager
    version: v1.10.0
    repository: https://charts.jetstack.io
    
How to fix it?

**Comment by caerulescens** [comment]
I thought this issue regressed while solving a different problem, and I can confirm that this isn't an issue in `cert-manager==1.13.2`. ArgoCD + istio + cert-manager network boots correctly, and routes signed traffic using sidecar proxies as expected.

**Comment by p33t00** [comment]
Isn't "installCRDs" deprecated and crds.enabled: true is to be used instead ?
