### ISSUE TITLE
StatefulSet PVC always out of sync when created by Helm

### ISSUE THREAD

**Issue by ddonnen** [argoproj/argo-cd#4242]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When creating an application that includes a StatefulSet with volumeClaimTemplates, the persistent volumes claims are always out of sync and are marked to be pruned

**To Reproduce**

Create an application that includes a StatefulSet with volumeClaimTemplates from a helm chart, e.g. Solr
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample
  namespace: argocd
spec:
  destination:
    namespace: sample
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: solr
    repoURL: https://kubernetes-charts-incubator.storage.googleapis.com/
    targetRevision: 1.5.2
```

**Expected behavior**

The persistent volumes claims should not be out of sync and I think they should be shown as a child of the StatefulSet. If I set fullnameOverride to "solr", the pods and pvcs are shown as children of the solr stateful set.

**Screenshots**

![image](https://user-images.githubusercontent.com/41022595/92026659-5267c680-ed2f-11ea-89d4-f0c6cf93aebd.png)

When applying fullnameOverride in chart, the pods and pvcs are shown as children of the solr stateful set.

![image](https://user-images.githubusercontent.com/41022595/92027678-e2f2d680-ed30-11ea-83ae-0561acc99212.png)

**Version**

```shell
argocd: v1.7.2+c342d3f
  BuildDate: 2020-08-27T23:33:37Z
  GitCommit: c342d3fc9c9c9f0d1c18254b6ffa1e106984a76c
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.7.2+c342d3f
  BuildDate: 2020-08-27T23:34:52Z
  GitCommit: c342d3fc9c9c9f0d1c18254b6ffa1e106984a76c
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}   
  Kubectl Version: v1.17.8
```

Not sure if I should have opened this in gitops-engine because it seems like the logic introduced in https://github.com/argoproj/gitops-engine/pull/127 doesn't work with Helm "ReleaseName-Name" style named resources.

**Comment by jessesuen** [comment]
Argo CD v1.7 was supposed to artificially create a parent/child relationship between StatefulSet and PVC, in order to prevent this scenario, but it appears there are some scenarios where this isn't working.

**Comment by boundless-thread** [comment]
I can confirm this behavior. However it is not always out of sync for me.  I have several applications that have long init container runtimes, and all of them appear out of sync. Several other applications have smaller init container runtimes and the dependency is established (synced).  Time may not be a factor here, but its what I've noticed in my case. 

I am also using Helm.

**Comment by jessesuen** [comment]
Fixed

**Comment by RamazanKara** [comment]
Still valid for us. Happens with statefulsets like Loki in combination with PVC Creation with the default gp2 EKS Storage Class

**Comment by mananpreetsingh** [comment]
+1, It still happens when we setup Loki-stack with persistence volume enabled.

**Comment by anthonyalayo** [comment]
+1, also with Loki

**Comment by ivanaguilario** [comment]
Same here with Loki and Mimir

**Comment by d-mahard** [comment]
same here, sonarqube helm (to be specific, postgresql for sonarqube)

![image](https://github.com/argoproj/argo-cd/assets/146386738/b923408d-6951-4225-8286-bd1727af6a52)

the helm: https://SonarSource.github.io/helm-chart-sonarqube
the manifest of the sts resource: https://github.com/SonarSource/helm-chart-sonarqube/blob/ab450bc36060b5724578edd8bfb5b45b82379388/charts/sonarqube/templates/sonarqube-sts.yaml

effectively as follows (the one in the link above uses vars everywhere, so when resolved it looks like the following)
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: null
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: sonarqube
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.15.0
  name: sonarqube-postgresql
  namespace: dev-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: sonarqube
      app.kubernetes.io/name: postgresql
      role: primary
  serviceName: sonarqube-postgresql-headless
  template:
    metadata:
      labels:
        app.kubernetes.io/component: primary
        app.kubernetes.io/instance: sonarqube
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: postgresql
        helm.sh/chart: postgresql-10.15.0
        role: primary
      name: sonarqube-postgresql
    spec:
      affinity:
        nodeAffinity: null
        podAffinity: null
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/component: primary
                    app.kubernetes.io/instance: sonarqube
                    app.kubernetes.io/name: postgresql
                namespaces:
                  - dev-tools
                topologyKey: kubernetes.io/hostname
              weight: 1
      automountServiceAccountToken: false
      containers:
        - env:
            - name: BITNAMI_DEBUG
              value: 'false'
            - name: POSTGRESQL_PORT_NUMBER
              value: '5432'
            - name: POSTGRESQL_VOLUME_DIR
              value: /bitnami/postgresql
            - name: PGDATA
              value: /bitnami/postgresql/data
            - name: POSTGRES_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgresql-postgres-password
                  name: sonarqube-postgresql
            - name: POSTGRES_USER
              value: sonarUser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgresql-password
                  name: sonarqube-postgresql
            - name: POSTGRES_DB
              value: sonarDB
            - name: POSTGRESQL_ENABLE_LDAP
              value: 'no'
            - name: POSTGRESQL_ENABLE_TLS
              value: 'no'
            - name: POSTGRESQL_LOG_HOSTNAME
              value: 'false'
            - name: POSTGRESQL_LOG_CONNECTIONS
              value: 'false'
            - name: POSTGRESQL_LOG_DISCONNECTIONS
              value: 'false'
            - name: POSTGRESQL_PGAUDIT_LOG_CATALOG
              value: 'off'
            - name: POSTGRESQL_CLIENT_MIN_MESSAGES
              value: error
            - name: POSTGRESQL_SHARED_PRELOAD_LIBRARIES
              value: pgaudit
          image: 'docker.io/bitnami/postgresql:11.14.0-debian-10-r22'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - '-c'
                - >-
                  exec pg_isready -U "sonarUser" -d "dbname=sonarDB" -h
                  127.0.0.1 -p 5432
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: sonarqube-postgresql
          ports:
            - containerPort: 5432
              name: tcp-postgresql
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-c'
                - '-e'
                - >
                  exec pg_isready -U "sonarUser" -d "dbname=sonarDB" -h
                  127.0.0.1 -p 5432

                  [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f
                  /bitnami/postgresql/.initialized ]
            failureThreshold: 6
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 200Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /bitnami/postgresql
              name: data
              subPath: null
      securityContext:
        fsGroup: 1001
      volumes:
        - emptyDir:
            medium: Memory
          name: dshm
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi

```

**Comment by WillyRL** [comment]
> same here, sonarqube helm (to be specific, postgresql for sonarqube)
> 
> ![image](https://private-user-images.githubusercontent.com/146386738/318580692-b923408d-6951-4225-8286-bd1727af6a52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NTYyMzYsIm5iZiI6MTcyNTk1NTkzNiwicGF0aCI6Ii8xNDYzODY3MzgvMzE4NTgwNjkyLWI5MjM0MDhkLTY5NTEtNDIyNS04Mjg2LWJkMTcyN2FmNmE1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQwODEyMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjAyODYyNzBhOTU1OTFiZjgyMjdhNzYyM2Y1OThiZjI1ODJlZWQ1MTJhODI3NWI1ODk0MjZlNmY3MzBmZWM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._ZFfDNJ19IwX8h2tlnws4BZeRa_QMMuwsO9HD5_AiJo)
> 
> the helm: https://SonarSource.github.io/helm-chart-sonarqube the manifest of the sts resource: https://github.com/SonarSource/helm-chart-sonarqube/blob/ab450bc36060b5724578edd8bfb5b45b82379388/charts/sonarqube/templates/sonarqube-sts.yaml
> 
> effectively as follows (the one in the link above uses vars everywhere, so when resolved it looks like the following)
> 
> ```
> apiVersion: apps/v1
> kind: StatefulSet
> metadata:
>   annotations: null
>   labels:
>     app.kubernetes.io/component: primary
>     app.kubernetes.io/instance: sonarqube
>     app.kubernetes.io/managed-by: Helm
>     app.kubernetes.io/name: postgresql
>     helm.sh/chart: postgresql-10.15.0
>   name: sonarqube-postgresql
>   namespace: dev-tools
> spec:
>   replicas: 1
>   selector:
>     matchLabels:
>       app.kubernetes.io/instance: sonarqube
>       app.kubernetes.io/name: postgresql
>       role: primary
>   serviceName: sonarqube-postgresql-headless
>   template:
>     metadata:
>       labels:
>         app.kubernetes.io/component: primary
>         app.kubernetes.io/instance: sonarqube
>         app.kubernetes.io/managed-by: Helm
>         app.kubernetes.io/name: postgresql
>         helm.sh/chart: postgresql-10.15.0
>         role: primary
>       name: sonarqube-postgresql
>     spec:
>       affinity:
>         nodeAffinity: null
>         podAffinity: null
>         podAntiAffinity:
>           preferredDuringSchedulingIgnoredDuringExecution:
>             - podAffinityTerm:
>                 labelSelector:
>                   matchLabels:
>                     app.kubernetes.io/component: primary
>                     app.kubernetes.io/instance: sonarqube
>                     app.kubernetes.io/name: postgresql
>                 namespaces:
>                   - dev-tools
>                 topologyKey: kubernetes.io/hostname
>               weight: 1
>       automountServiceAccountToken: false
>       containers:
>         - env:
>             - name: BITNAMI_DEBUG
>               value: 'false'
>             - name: POSTGRESQL_PORT_NUMBER
>               value: '5432'
>             - name: POSTGRESQL_VOLUME_DIR
>               value: /bitnami/postgresql
>             - name: PGDATA
>               value: /bitnami/postgresql/data
>             - name: POSTGRES_POSTGRES_PASSWORD
>               valueFrom:
>                 secretKeyRef:
>                   key: postgresql-postgres-password
>                   name: sonarqube-postgresql
>             - name: POSTGRES_USER
>               value: sonarUser
>             - name: POSTGRES_PASSWORD
>               valueFrom:
>                 secretKeyRef:
>                   key: postgresql-password
>                   name: sonarqube-postgresql
>             - name: POSTGRES_DB
>               value: sonarDB
>             - name: POSTGRESQL_ENABLE_LDAP
>               value: 'no'
>             - name: POSTGRESQL_ENABLE_TLS
>               value: 'no'
>             - name: POSTGRESQL_LOG_HOSTNAME
>               value: 'false'
>             - name: POSTGRESQL_LOG_CONNECTIONS
>               value: 'false'
>             - name: POSTGRESQL_LOG_DISCONNECTIONS
>               value: 'false'
>             - name: POSTGRESQL_PGAUDIT_LOG_CATALOG
>               value: 'off'
>             - name: POSTGRESQL_CLIENT_MIN_MESSAGES
>               value: error
>             - name: POSTGRESQL_SHARED_PRELOAD_LIBRARIES
>               value: pgaudit
>           image: 'docker.io/bitnami/postgresql:11.14.0-debian-10-r22'
>           imagePullPolicy: IfNotPresent
>           livenessProbe:
>             exec:
>               command:
>                 - /bin/sh
>                 - '-c'
>                 - >-
>                   exec pg_isready -U "sonarUser" -d "dbname=sonarDB" -h
>                   127.0.0.1 -p 5432
>             failureThreshold: 6
>             initialDelaySeconds: 30
>             periodSeconds: 10
>             successThreshold: 1
>             timeoutSeconds: 5
>           name: sonarqube-postgresql
>           ports:
>             - containerPort: 5432
>               name: tcp-postgresql
>           readinessProbe:
>             exec:
>               command:
>                 - /bin/sh
>                 - '-c'
>                 - '-e'
>                 - >
>                   exec pg_isready -U "sonarUser" -d "dbname=sonarDB" -h
>                   127.0.0.1 -p 5432
> 
>                   [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f
>                   /bitnami/postgresql/.initialized ]
>             failureThreshold: 6
>             initialDelaySeconds: 5
>             periodSeconds: 10
>             successThreshold: 1
>             timeoutSeconds: 5
>           resources:
>             limits:
>               cpu: 2
>               memory: 2Gi
>             requests:
>               cpu: 100m
>               memory: 200Mi
>           securityContext:
>             allowPrivilegeEscalation: false
>             capabilities:
>               drop:
>                 - ALL
>             runAsNonRoot: true
>             runAsUser: 1001
>             seccompProfile:
>               type: RuntimeDefault
>           volumeMounts:
>             - mountPath: /dev/shm
>               name: dshm
>             - mountPath: /bitnami/postgresql
>               name: data
>               subPath: null
>       securityContext:
>         fsGroup: 1001
>       volumes:
>         - emptyDir:
>             medium: Memory
>           name: dshm
>   updateStrategy:
>     type: RollingUpdate
>   volumeClaimTemplates:
>     - metadata:
>         name: data
>       spec:
>         accessModes:
>           - ReadWriteOnce
>         resources:
>           requests:
>             storage: 20Gi
> ```

Hi @d-mahard Have you found the solution for this ?
