### ISSUE TITLE
Certificate resources from cert-manager v1 fails / syncing becomes stuck

### ISSUE THREAD

**Issue by servo1x** [argoproj/argo-cd#4275]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When creating a `Certificate` from cert-manager (v1), and using a sync-wave or hook, the sync immediately fails: with `Issuing certificate as Secret does not exist`. This causes ArgoCD to retry the sync 7 hours later (?):

```
Running a few seconds ago (Sat Sep 05 2020 03:30:53 GMT-0700)
one or more synchronization tasks completed unsuccessfully. Retrying attempt #1 at 10:28AM.
```

We're not able to resync when using `pre-sync`. When using `sync-wave`, if we terminate the sync and sync again it works.

Do we need to create a custom healthcheck or something?

**To Reproduce**

Create a `Certificate` with the `hook` or `sync-wave` annotation:

```yaml
# fails immediately and unable to sync even when retrying
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
...

# sync remains stuck
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
...
```

**Expected behavior**

ArgoCD should ignore the secretName does not exist error and continue syncing when using hook or sync-wave annotations.

**Version**

```shell
argocd: v1.7.4+f8cbd6b
  BuildDate: 2020-09-05T02:46:53Z
  GitCommit: f8cbd6bf432327cc3b0f70d23b66511bb906a178
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.7.4+f8cbd6b
  BuildDate: 2020-09-05T02:45:44Z
  GitCommit: f8cbd6bf432327cc3b0f70d23b66511bb906a178
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
  Kubectl Version: v1.17.8
```

**Comment by jessesuen** [comment]
This seems to be cause by the Certificate health check. The workaround is to disable the health check for Certificates through the argocd-cm resource_customization configuration.

**Comment by servo1x** [comment]
@jessesuen by disable do you mean adding something like this?

```yaml
certmanager.k8s.io/Certificate:
   health.lua: |
       hs = {}
       hs.status = "Healthy"
       return hs
```

**Comment by aliusmiles** [comment]
seems to work for me with this https://argoproj.github.io/argo-cd/operator-manual/health/#way-1-define-a-custom-health-check-in-argocd-cm-configmap but need to do some deployments to confirm -- not sure if custom healthcheck helped or me terminating sync

**Comment by aliusmiles** [comment]
It appears that cert-manager custom healthcheck is already bundled into Argo CD:  [health.lua](https://github.com/argoproj/argo-cd/blob/v1.7.7/resource_customizations/cert-manager.io/Certificate/health.lua),  [docs](https://argoproj.github.io/argo-cd/operator-manual/health/#way-2-contribute-a-custom-health-check), so no need for argocd-cm modifications.

so it should work by default, and it indeed work if ArgoCD Application is creating only cert-manager resources or there are no hooks or sync waves annotations on cert resources. But when trying to control certs creation order by hooks or sync waves, then ArgoCD gets stuck at Sync. 

Wild guess: hooks/sync waves ignore custom healthchecks?

Here's my setup:
* custom chart 
* official logstash as dependency chart
* create logstash CA Certificate from selfsigner ClusterIssuer
* create logstash Issuer based on logstash CA
* create logstash Certificate from logstash Issuer
* create filebeat Certificate from logstash Issuer

Tried following (ArgoCD 1.7.7, certmanager v1.0.2):

#### cert resources as separate chart/argocd app

works just fine, everything healthy and synced, though cert resources are briefly shown as 'degraded' in argocd ui

#### Cert resources as part of umbrella char with SyncWaves annotation on them

CA created, everything else is OutOfSync, Sync is running, message: `waiting for healthy state of cert-manager.io/Issuer/logstash-issuer`

#### Cert resources as part of umbrella char with PreSync hook annotation on them

all certs resources created, then start disappear/appear in agocd UI, app stuck at Sync, 
message: `waiting for completion of hook cert-manager.io/Certificate/filebeat-tls and 10 more hooks`

#### Cert resources as part of umbrella char, no annotations

everything is created, though cert resources are briefly shown as *degraded*, but logstash pod obviously fails to start first time due to `MountVolume.SetUp failed for volume "logstash-tls" : secret "logstash-tls" not found`. So ArgoCD App is *Pending* for some time until pod gets restarted and picks secret up.

**Comment by roshpr** [comment]
@aliusmiles where you able to workaround this issue? I too am seeing similar issue with kind certificate from certificate manager with argo hooks.

**Comment by aliusmiles** [comment]
@roshpr no, and I don't use argocd anymore, so can't reproduce with latest versions.

**Comment by roshpr** [comment]
@aliusmiles sad to see u gone.
@jessesuen would you be able to help? Any help will be much appreciated. 

**Argo version**: Tried both : "1.8.7" & "2.0.0"
My Certificate config has got helm hooks configured
```
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: '-5'
```
Argo is overriding the same with Argo sync hooks as per document. The provisioning fails with error **"Issuing certificate as Secret does not exist"** . All the other Deployment resources are blocked on this since Certificate provisioning is failing as Failed or Degraded.

**Certificate config**
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: '-5'
  labels:
    app.kubernetes.io/instance: storage
  name: storage-cert
  namespace: atom-storage
spec:
  commonName: storage.atom-storage
  issuerRef:
    kind: ClusterIssuer
    name: commoncaissuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    rotationPolicy: Always
    size: 2048
  renewBefore: 360h0m0s
  secretName: storage-atom-storage-tls
  subject:
    organizations:
      - xxxxx
```
**Deployment config**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: storage
  name: storage
  namespace: atom-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: storage
      app.kubernetes.io/name: storage
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: storage
        app.kubernetes.io/name: storage
    spec:
      containers:
        - args:
            - '--config=/etc/storage/config/config.json'
            - '--level=info'
          image: >-
            storage:1.2.0-g1d2e72a864
          imagePullPolicy: IfNotPresent

          name: storage
          ports:
            - containerPort: 8080
              name: https
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/storage/config/certs
              name: tls-certs
            - mountPath: /etc/storage/config
              name: config
      volumes:
        - name: tls-certs
          secret:
            secretName: storage-atom-storage-tls
        - configMap:
            name: storage-config
          name: config
```

**Health check applied for certificate**
```
  resource.customizations: |
    cert-manager.io/Certificate:
      health.lua: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.conditions ~= nil then
            for i, condition in ipairs(obj.status.conditions) do
              if condition.type == "Ready" and condition.status == "False" and obj.metadata.namespace ~= "external-dns" then
                hs.status = "Degraded"
                hs.message = condition.message
                return hs
              end
              if condition.type == "Ready" and condition.status == "True" then
                hs.status = "Healthy"
                hs.message = condition.message
                return hs
              end
            end
          end
        end

        hs.status = "Progressing"
        hs.message = "Waiting for certificate"
        return hs
```
I also noticed a similar error being spoken of in issue https://github.com/argoproj/argo-cd/issues/1826 . It seemed to have moved as fixed. I still see the issue. Am I missing some thing?

**Comment by roshpr** [comment]
> @aliusmiles sad to see u gone.
> @jessesuen would you be able to help? Any help will be much appreciated.
> 
> **Argo version**: Tried both : "1.8.7" & "2.0.0"
> My Certificate config has got helm hooks configured
> 
> ```
>   annotations:
>     helm.sh/hook: pre-install
>     helm.sh/hook-weight: '-5'
> ```
> 
> Argo is overriding the same with Argo sync hooks as per document. The provisioning fails with error **"Issuing certificate as Secret does not exist"** . All the other Deployment resources are blocked on this since Certificate provisioning is failing as Failed or Degraded.
> 
> **Certificate config**
> 
> ```
> apiVersion: cert-manager.io/v1
> kind: Certificate
> metadata:
>   annotations:
>     helm.sh/hook: pre-install
>     helm.sh/hook-weight: '-5'
>   labels:
>     app.kubernetes.io/instance: storage
>   name: storage-cert
>   namespace: atom-storage
> spec:
>   commonName: storage.atom-storage
>   issuerRef:
>     kind: ClusterIssuer
>     name: commoncaissuer
>   privateKey:
>     algorithm: RSA
>     encoding: PKCS1
>     rotationPolicy: Always
>     size: 2048
>   renewBefore: 360h0m0s
>   secretName: storage-atom-storage-tls
>   subject:
>     organizations:
>       - xxxxx
> ```
> 
> **Deployment config**
> 
> ```
> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   labels:
>     app.kubernetes.io/name: storage
>   name: storage
>   namespace: atom-storage
> spec:
>   replicas: 1
>   selector:
>     matchLabels:
>       app.kubernetes.io/instance: storage
>       app.kubernetes.io/name: storage
>   template:
>     metadata:
>       labels:
>         app.kubernetes.io/instance: storage
>         app.kubernetes.io/name: storage
>     spec:
>       containers:
>         - args:
>             - '--config=/etc/storage/config/config.json'
>             - '--level=info'
>           image: >-
>             storage:1.2.0-g1d2e72a864
>           imagePullPolicy: IfNotPresent
> 
>           name: storage
>           ports:
>             - containerPort: 8080
>               name: https
>               protocol: TCP
>           volumeMounts:
>             - mountPath: /etc/storage/config/certs
>               name: tls-certs
>             - mountPath: /etc/storage/config
>               name: config
>       volumes:
>         - name: tls-certs
>           secret:
>             secretName: storage-atom-storage-tls
>         - configMap:
>             name: storage-config
>           name: config
> ```
> 
> **Health check applied for certificate**
> 
> ```
>   resource.customizations: |
>     cert-manager.io/Certificate:
>       health.lua: |
>         hs = {}
>         if obj.status ~= nil then
>           if obj.status.conditions ~= nil then
>             for i, condition in ipairs(obj.status.conditions) do
>               if condition.type == "Ready" and condition.status == "False" and obj.metadata.namespace ~= "external-dns" then
>                 hs.status = "Degraded"
>                 hs.message = condition.message
>                 return hs
>               end
>               if condition.type == "Ready" and condition.status == "True" then
>                 hs.status = "Healthy"
>                 hs.message = condition.message
>                 return hs
>               end
>             end
>           end
>         end
> 
>         hs.status = "Progressing"
>         hs.message = "Waiting for certificate"
>         return hs
> ```
> 
> I also noticed a similar error being spoken of in issue #1826 . It seemed to have moved as fixed. I still see the issue. Am I missing some thing?

The issue got resolved with moving to ArgoCD 2.0

**Comment by servo1x** [comment]
No longer seeing this issue.

**Comment by joaosilva15** [comment]
Hello. I still see this issue. In my case, I see that while the certificate is being issued there are two conditions. 
```
conditions:
  - lastTransitionTime: "2021-08-24T10:06:26Z"
    message: Issuing certificate as Secret does not exit
    observedGeneration: 1
    reason: DoesNotExist
    status: "True"
    type: Issuing
 - lastTransitionTime: "2021-08-24T10:06:26Z"
    message: Issuing certificate as Secret does not exit
    observedGeneration: 1
    reason: DoesNotExist
    status: "False"
    type: Ready
```
I believe the second condition is being caught by the script and the resource is deemed as degraded.

Is this because I'm using an external provider for certmanager and should I change the validation script or is something lacking in the argocd builtin?

**Comment by teejaded** [comment]
@joaosilva15 can you try this resource customization?

https://github.com/teejaded/argo-cd/blob/cert-healthcheck-fix/resource_customizations/cert-manager.io/Certificate/health.lua

**Comment by joaosilva15** [comment]
Hey @teejaded, sorry for the loooong delay 🤦 just came to this issue again. Your changes work but I needed to change this line https://github.com/teejaded/argo-cd/blob/cert-healthcheck-fix/resource_customizations/cert-manager.io/Certificate/health.lua#L5 from `condition.Reason` to `condition.reason`

**Comment by hlacikd** [comment]
guys, i do use this
`
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  resource.customizations.health.cert-manager.io_Certificate: |
    hs = {}
    if obj.status ~= nil then
      if obj.status.conditions ~= nil then
        for i, condition in ipairs(obj.status.conditions) do
          if condition.type == "Ready" and condition.status == "False" and condition.reason ~= "DoesNotExist" then
            hs.status = "Degraded"
            hs.message = condition.message
            return hs
          end
          if condition.type == "Ready" and condition.status == "True" and condition.reason ~= "DoesNotExist" then
            hs.status = "Healthy"
            hs.message = condition.message
            return hs
          end
        end
      end
    end
    hs.status = "Progressing"
    hs.message = "Waiting for certificate"
    return hs
`

**Comment by caerulescens** [comment]
Experiencing the same thing as @hlacikd

**Comment by L-U-C-K-Y** [comment]
I also encountered this issue. For now I have removed the cert from gitops and deployed it manually.

**Comment by CyberTr4der** [comment]
> 

same temporary workaround atm :-(

**Comment by hlacikd** [comment]
probably new bug needs to be opened, since this one is closed, could you guys please do so?

**Comment by caerulescens** [comment]
@hlacikd @CryptoTr4der @L-U-C-K-Y Try this and let me know:

```
cert-manager.io/Certificate:
          health.lua: |
            hs = {}
            if obj.status ~= nil then
              if obj.status.conditions ~= nil then
                for i\, condition in ipairs(obj.status.conditions) do
                  if condition.type == "Ready" and condition.status == "False" then
                    hs.status = "Degraded"
                    hs.message = condition.message
                    return hs
                  end
                  if condition.type == "Ready" and condition.status == "True" then
                    hs.status = "Healthy"
                    hs.message = condition.message
                    return hs
                  end
                end
              end
            end

            hs.status = "Progressing"
            hs.message = "Waiting for certificate"
            return hs
```

**Comment by initialed85** [comment]
> @hlacikd @CryptoTr4der @L-U-C-K-Y I had a thrashing issue, and I solved it with the below; try it and let me know.
> 
> Under `configs.cm.resource.customizations`, set the value:
> 
> ```
> cert-manager.io/Certificate:
>           health.lua: |
>             hs = {}
>             if obj.status ~= nil then
>               if obj.status.conditions ~= nil then
>                 for i, condition in ipairs(obj.status.conditions) do
>                   if condition.type == "Ready" and condition.status == "False" then
>                     hs.status = "Degraded"
>                     hs.message = condition.message
>                     return hs
>                   end
>                   if condition.type == "Ready" and condition.status == "True" then
>                     hs.status = "Healthy"
>                     hs.message = condition.message
>                     return hs
>                   end
>                 end
>               end
>             end
> 
>             hs.status = "Progressing"
>             hs.message = "Waiting for certificate"
>             return hs
> ```

I was getting the same thing, can confirm this worked for me, Argo CD v2.7.4, cert-manager v1.12.2
