### ISSUE TITLE
Broken CLI "app wait" command after server upgrade to v1.7.4

### ISSUE THREAD

**Issue by alinbalutoiu** [argoproj/argo-cd#4321]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

After upgrading the ArgoCD server to `v1.7.4`, there is an issue with `argocd app wait` on the client side. The command returns a timeout error even when the application is synced and healthy.
This worked fine for ArgoCD server versions prior to `v1.7.4` (even with `v1.7.3` as someone else confirmed).
The timeouts are happening only when using a `v1.7.x` CLI, using a `v1.6.x` version of the CLI works as expected.

Timeout error example:
```
WARN[0060] watch err: rpc error: code = Unknown desc = POST https://argocd.server.tld:443/application.ApplicationService/Watch failed with status code 504
```

**To Reproduce**

- Setup a `v1.7.4` ArgoCD server;

- Get any CLI from the `v1.7.x` releases;

- Setup a test application;

```shell
$ argocd app wait gitops-demo --timeout 10

Name:               gitops-demo
Project:            <redacted>
Server:             <redacted>
Namespace:          gitops
URL:                <redacted>
Repo:               <redacted>
Target:             HEAD
Path:               kube-manifests
SyncWindow:         Sync Allowed
Sync Policy:        <none>
Sync Status:        Synced to HEAD (1df93f2)
Health Status:      Healthy

Operation:          Sync
Sync Revision:      1df93f2c2d9cd72848731e013845099f5f742ff7
Phase:              Succeeded
Start:              2020-09-14 14:56:22 +0200 CEST
Finished:           2020-09-14 14:56:24 +0200 CEST
Duration:           2s
Message:            successfully synced (all tasks run)

GROUP       KIND            NAMESPACE  NAME                       STATUS  HEALTH   HOOK  MESSAGE
            ServiceAccount  gitops     gitops-serviceaccount      Synced                 serviceaccount/gitops-serviceaccount unchanged
            Service         gitops     gitops-service             Synced  Healthy        service/gitops-service unchanged
apps        Deployment      gitops     gitops-app-v5              Synced  Healthy        deployment.apps/gitops-app-v5 configured
extensions  Ingress         gitops     demo-gitops-ingress-https  Synced  Healthy        ingress.extensions/demo-gitops-ingress-https unchanged
FATA[0010] timed out (10s) waiting for app "gitops-demo" match desired state
$ echo $?
20
```

**Expected behavior**

Expecting the `app wait` command to work fine. The expected behavior can be seen with the older CLI versions.

Example working with a previous CLI version (same ArgoCD server):
```shell
$ ./argocd-linux-amd64 version
argocd: v1.6.2+3d1f37b
  BuildDate: 2020-07-31T23:43:46Z
  GitCommit: 3d1f37b0c53f4c75864dc7339e2831c6e6a947e0
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
$ ./argocd-linux-amd64 app wait gitops-demo

Name:               gitops-demo
Project:            <redacted>
Server:             <redacted>
Namespace:          gitops
URL:                <redacted>
Repo:               <redacted>
Target:             HEAD
Path:               kube-manifests
SyncWindow:         Sync Allowed
Sync Policy:        <none>
Sync Status:        Synced to HEAD (1df93f2)
Health Status:      Healthy

Operation:          Sync
Sync Revision:      1df93f2c2d9cd72848731e013845099f5f742ff7
Phase:              Succeeded
Start:              2020-09-14 14:56:22 +0200 CEST
Finished:           2020-09-14 14:56:24 +0200 CEST
Duration:           2s
Message:            successfully synced (all tasks run)

GROUP       KIND            NAMESPACE  NAME                       STATUS  HEALTH   HOOK  MESSAGE
            ServiceAccount  gitops     gitops-serviceaccount      Synced                 serviceaccount/gitops-serviceaccount unchanged
            Service         gitops     gitops-service             Synced  Healthy        service/gitops-service unchanged
apps        Deployment      gitops     gitops-app-v5              Synced  Healthy        deployment.apps/gitops-app-v5 configured
extensions  Ingress         gitops     demo-gitops-ingress-https  Synced  Healthy        ingress.extensions/demo-gitops-ingress-https unchanged
$ echo $?
0
```

**Version**

```shell
$ argocd version
argocd: v1.7.4+f8cbd6b
  BuildDate: 2020-09-05T02:44:27Z
  GitCommit: f8cbd6bf432327cc3b0f70d23b66511bb906a178
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.7.4+f8cbd6b
  BuildDate: 2020-09-05T02:45:44Z
  GitCommit: f8cbd6bf432327cc3b0f70d23b66511bb906a178
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
```

**Comment by BioSin** [comment]
🐛 I had the same bug, downgrade to 1.6.2 fixed the issue.

**Comment by alexmt** [comment]
1.7 has introduced deadlock in API server. It is possible that one api-server pod permanently goes into bad state and `argocd app wait` times out if request is served by affected pod. 

I doubt downgrading CLI to v1.6.2 solves the problem, it could be a coincidence. The fix had been implemented already. We rolled out it internally and will know by end of day if it is not reproducible anymore.

**Comment by mcanevet** [comment]
I don't know if it's the same issue, but I have my app of apps' sync that never finishes since upgrade to 1.7.5. It says `waiting for healthy state of argoproj.io/Application/prometheus-operator and 5 more resources` even though all my other apps are `Synced` and `Healthy`. It was working fine with 1.6.2.

**Comment by alexmojo** [comment]
Same issue here. 
After executing 
```argocd app sync <app-name>``` 
utility seems to be hanging forever and never finish operation even though application is synced and healthy. If I use CLI version ```1.6.2```,  ```sync``` operation also hanging, but atleast it print  state of resources
```
 argocd app sync print-host-app
TIMESTAMP                  GROUP             KIND   NAMESPACE                  NAME                                             STATUS   HEALTH        HOOK  MESSAGE
2020-09-16T16:08:33+00:00                 Service   tech-team  print-host-svc    Synced  Healthy
2020-09-16T16:08:33+00:00   apps       Deployment   tech-team  print-host                                   Synced  Healthy
2020-09-16T16:08:33+00:00  extensions     Ingress   tech-team  print-host-ing    Synced  Healthy
```
but never complete execution
argocd version ```1.7.4```

**Comment by alexmt** [comment]
Hello @mcanevet , @alexmojo . I keep trying to find the possible reason. Is the issue reproducible consistently or happens intermittently?

**Comment by alexmojo** [comment]
@alexmt, hi! This issue reproducing constantly. But I've noticed that restarting argo-server pods resolving this issue for some time. We are running argocd in HA mode, with 2 argocd-server pods. 
Also, I've noticed that argocd-server pods are constanlty killed with OOM ( I guess it is related to #4298). All this issues are constantly observed after upgrading to 1.7
I will upgrade today to version 1.7.5 and share results tomorrow

**Comment by alexmt** [comment]
@alexmojo I'm 99% sure this is fixed in 1.7.5. API had a deadlock and OOM is one of symptoms. Trying to find what happened with app of apps

**Comment by mcanevet** [comment]
@alexmt maybe my issue is not exactly the same. I observe it also in the web ui, not only using the CLI. And only on the app of apps. And 1.7.5 didn't fixed the issue. I have a pipeline that allows me to recreate my cluster from scratch and I can confirm that it happens every time since I upgraded to 1.7 (now I downgraded to 1.6.2 because of this issue, but I can upgrade and respawn everything if you need to test something).

**Comment by alexmt** [comment]
hello @mcanevet ,

Thank you for update. Still trying to reproduce issue. Good to know it is related to app-of-apps. Hope to find root cause tomorrow.

**Comment by bitfactory-henno-schooljan** [comment]
I also have timeouts on an app that does not contain apps, it 504's a few times and eventually completes waiting. Sometimes it is instant. Both server and CLI on v1.7.5.

**Comment by alinbalutoiu** [comment]
I'm still having the same issue as described in the original post after upgrading to ArgoCD 1.7.5.

```
$ argocd version
argocd: v1.7.5+90cc56c
  BuildDate: 2020-09-15T23:02:33Z
  GitCommit: 90cc56c3a99127f6ed6bcb777abf92e357c1eb00
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.7.5+90cc56c
  BuildDate: 2020-09-15T23:03:57Z
  GitCommit: 90cc56c3a99127f6ed6bcb777abf92e357c1eb00
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8
```

Using the CLI 1.6.2 with ArgoCD server 1.7.5 still works fine for the `app wait` command.

**Comment by jessesuen** [comment]
Fixed in https://github.com/argoproj/argo-cd/pull/4350 (will be available in v1.7.6)

**Comment by hanzala1234** [comment]
I am facing the same issue as @mcanevet and I am having a 1.7.7 version of argocd. Above fix does not seem to solve our issue
