### ISSUE TITLE
ArgoCD UI just keeps on refreshing even if the Pod is in Failed/Completed State 

### ISSUE THREAD

**Issue by rajivml** [argoproj/argo-cd#4721]
Environment: 1.7.8

# Summary

HI, 

When we are on the Pod logs page, even if the job is in failed/completed state, the UI just keeps on polling the backend to fetch the latest logs and it makes copying the logs very difficult not difficult but almost impossible 

# Motivation

Am trying to copy the logs from pod logs UI , but UI just keeps on polling backend and content is getting refreshed even after the Pod is in Failed/Completed state

# Proposal

Stop polling when the job is failed/completed state

**Comment by rajivml** [comment]
Recorded a short demo here about the issue:

https://uipath.zoom.us/rec/share/GfcDP51kTdsTjI9SM0pZLLsZV-WGdTDCg4eHKkxciEon-J6_25Y6VBm-atDZbDMl.2VqYwGrUItQDUfE0

Access Passcode: 7Zeq!#AD

**Comment by jannfis** [comment]
This might be the for the same reason as reported in #4619, which was fixed by #4696 to be released with v1.8.

**Comment by rajivml** [comment]
Thanks @jannfis for looking into this, I will use 1.7.4 for my demo in that case

**Comment by rajivml** [comment]
@jannfis I have downgraded to 1.7.4 but I do see this issue there as well but not as bad as 1.7.8 but the issue is still there... If I click on refresh then the polling gets stopped till then even though pod completes its execution pod will be still shown as running and logs keep on getting override

**Comment by jessesuen** [comment]
Closing as duplicate of https://github.com/argoproj/argo-cd/issues/4619
