### ISSUE TITLE
failed to convert *unstructured.Unstructured to *v1beta1.Ingress: no kind "Ingress" is registered for version "networking.k8s.io/v1" 

### ISSUE THREAD

**Issue by boniek83** [argoproj/argo-cd#6222]
**Describe the bug**
I get this annoying error when using v1 ingress:
```
ComparisonError
failed to convert *unstructured.Unstructured to *v1beta1.Ingress: no kind "Ingress" is registered for version "networking.k8s.io/v1" in scheme "pkg/runtime/scheme.go:101"
```
Funny thing is it sync anyway and it alternates between showing this error and not showing on Refresh.
**To Reproduce**

It happens when using networking.k8s.io/v1 Ingress in application

**Version**

```shell
$ argocd version
argocd: v2.0.1+33eaf11
  BuildDate: 2021-04-15T22:31:51Z
  GitCommit: 33eaf11e3abd8c761c726e815cbb4b6af7dcb030
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
```

**Comment by jessesuen** [comment]
Which kubernetes version are you using?

**Comment by Kvark1205** [comment]
Also got this error on our production cluster but fixed this through research. In our case we have ArgoCD with version v1.7.8+ef5010c and k8s v1.19.9. Hope this helps someone:

Because of one of the last k8s version, all it's ingress resources creates with networking.k8s.io/**v1** api. But in Argo v1.7.8 all our ingress templates writed in networking.k8s.io/**v1beta1** notation. In spite of this, every sync actions worked fine until I add new ingress directly in cluster for the same repo that Argo syncing. Argo sees that new ingress resource but it's not have ingress-template in git-repo at the moment.
It seems when Argo do syncing, k8s cluster converts delivered v1beta1 template to it's api version which is v1. After that notice I tried add new missing ingress template and update the others to v1 api notation but that not worked, error was the same (I suppose our old Argo version doesn't support networking.k8s.io/v1 api). Finally after rewriting templates to v1beta1 notation with missing ingress template solved this issue in my case.

Examples of v1beta1 and v1 notation you can find [here](https://stackoverflow.com/questions/63773116/how-to-convert-all-kubernetes-ingress-yamls-to-use-api-version-networking-k8s-io).

**Comment by boniek83** [comment]
> Which kubernetes version are you using?

v1.19.8

**Comment by cilindrox** [comment]
This is happening with argo 2.0.2 too. Seems to be related to the built-in templating library. The temporary patch is to fall back to another supported api like reported above.

**Comment by ofrivera** [comment]
Running into same issue when using `networking.k8s.io/v1`
```
Argo CD v2.0.3 
Kubernetes 1.19.9-gke.1900
```

**Comment by miwurster** [comment]
We experience the same issue. Just to recap and understand the full picture... The issue lies in Argo's template library, right? This means upgrading the cluster won't help. However, according to the comments above, changing the ingresses back to `networking.k8s.io/v1beta1` resolves the issue in ArgoCD?! Can anyone confirm this based on the latest versions?

```
ArgoCD v2.0.4
Kubernetes 1.20.8-gke.700
```

**Comment by cilindrox** [comment]
> This means upgrading the cluster won't help

This is my assumption as well. Haven't yet tested on k8s 1.22, but on 1.21 I'm seeing all sorts of issues with the `networking.k8s.io/v1` API for example.

Seems Argo is bundling an outdated Helm/apiserver library which lacks newer API versions and resources. This in turn makes some templates and checks fail due to a deprecated version being reported as available.

**Comment by jotacamou** [comment]
Bump.  Experiencing same issues even with v2.1.1 on GKE.

**Comment by ferdinandosimonetti** [comment]
Same of above, ArgoCD 2.1.2 (Helm chart argo-cd-3.17.6), Kubernetes 1.19.13-rancher1 (RKE).
Had to rollback to old resource API version, sigh.

**Comment by rbreeze** [comment]
This code should be rewritten to not depend on importing extensions.

https://github.com/rbreeze/gitops-engine/blob/master/pkg/health/health.go#L175-L188

**Comment by jessesuen** [comment]
> While planning to test the image I realized that I had 2 application controller pods. One of them from a deployment template running v1.0.7 and the other one from the more modern StatefulSet running the intended v2.1.2. 

Yes, that would absolutely cause the problem! It also explains the flapping in health status from green to red when you reproduced the issue. I'm actually surprised this was the only issue that you were facing given that you were running two controller pods with such drastic versions.

**Comment by eestolano** [comment]
Should this be reopened? The issue was fixed in the above gitops-engine PR, but it looks like argo-cd itself hasn't yet been updated to use a gitops-engine version containing the fix.

**Comment by beyondbill** [comment]
@eestolano The latest ArgoCD [v2.2.0](https://github.com/argoproj/argo-cd/blob/v2.2.0/go.mod#L11) updated gitops-engine to 0.5.1, which includes the [fix](https://github.com/argoproj/gitops-engine/commit/e8d9803a2bb015f9a7c64751bba63ef060bb0b26)!

**Comment by beyondbill** [comment]
@eestolano Sorry that did not fix the issue. I still see the following error after upgrading ArgoCD to v2.2.0

```
failed to convert *unstructured.Unstructured to *v1beta1.Ingress: no kind "Ingress" is registered for version "networking.k8s.io/v1" in scheme "pkg/runtime/scheme.go:101"
```

Can we reopen the issue as https://github.com/argoproj/gitops-engine/pull/335 did not really fix it

**Comment by Gowlar** [comment]
I am using v2.2.1+122ecef and same issue

**Comment by eestolano** [comment]
This appears to be time sensitive for those of us who have ingresses managed by ArgoCD on GKE:

* The beta version of the Ingress API is going away in GKE in Kubernetes v1.22: https://cloud.google.com/kubernetes-engine/docs/deprecations/apis-1-22#removed_apis_in_122
* We've received a notification from Google saying that they will delay automatic updates to Kubernetes 1.22 until March 2022, because they have detected that we're still using deprecated APIs that will be removed

That sounds like our GKE clusters will get forcibly upgraded to Kubernetes 1.22 in March 2022, and ArgoCD will thereby stop working properly for ingresses.

**Comment by hamza-tumturk** [comment]
The changes in https://github.com/argoproj/gitops-engine/pull/335 haven't fixed this issue.
This error might soon affect many people who are upgrading Kubernetes clusters to 1.20 and above. As stated by @eestolano in v1.22 you can't even use v1beta1 as a workaround anymore.

**Comment by MattLud** [comment]
This issue still affects argocd 2.6.2 on eks 1.22 as well. 

I'm seeing this constantly on one project to the point where I am going to blow the application away and recreate it.

**Comment by MattLud** [comment]
Removing the stale argocd-application-controller deployment and it looks to be clear now.
