### ISSUE TITLE
SSO login with multiple argocd-server replicas might fail with "unknown app state"

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#709]
We recently made it possible to run ArgoCD with multiple replicas. However one place where this doesn't work correctly is when we keep a OIDC state nonce in memory when completing an OAuth2 flow. After the redirect back to the API server, a different replica might handling the request than the one who originally initiated the OAuth2 flow, which results in the OIDC state nonce not being recognized since the nonces are kept in memory. This manifests itself in the following error in the browser:
`unknown app state <oidc state nonce>`

The workaround is to reattempt login and hope that you complete the OAauth2 login flow on the same replica which initialized the state nonce.

A longer term solution may be to store state nonces in some type of shared storage, or introduce some type of stickiness to the API server replicas.

**Comment by jessesuen** [comment]
I think we may be able to solve this with service level session affinity.

**Comment by jessesuen** [comment]
State nonces are now kept in redis so this is resolved

**Comment by rosscdh** [comment]
does not seem to be resolved 1.7.6 in HA

**Comment by limoges** [comment]
Happening with `dex:v2.22.0` and `argocd:v1.7.9` as well; didn't dig into the issue yet but definitely still happening;
We are using redis with haproxy.

**Comment by jessesuen** [comment]
https://github.com/argoproj/argo-cd/issues/5873 should allow us to avoid use of redis completely, during login.

**Comment by ksummersill2** [comment]
Was this ever resolved? If so what is the solution?

**Comment by nbarnes22** [comment]
I have an ArgoCD deployment in K8s, when I encountered this I simply deleted all of the pods and the deployment recreated them and this was solved.
