### ISSUE TITLE
Installing crds via argocd

### ISSUE THREAD

**Issue by amarrella** [argoproj/argo-cd#748]
Hi, since argocd does a dry run before actually syncronizing a specific application, if i have crds defined in the application itself the sync will fail. 

As a possible workaround, I tried creating a separate application pointing to a chart containing only the crds, but this fails the sync as the "application has no resources assigned".

Any solution to this catch-22? 
Thanks :)

**Comment by jessesuen** [comment]
@amarrella which version Argo CD are you running? We did have a bug exactly as you described about dry-run with CRDs, but this should be fixed in v0.10. 

Basically, we now have special treatment for CRDs such that we will not fail the dry-run step if the resource Kind does not exist, with the assumption that the CRD is part of the install.

**Comment by amarrella** [comment]
Hmm actually I'm still having issues with dry-runs. Specifically installing Istio via argocd still does not work because it fails during the dry run :( 
Using kubectl just works, but i would love to have it installed via argocd
```
helm template . --set ingress.enabled=false --set gateways.istio-egressgateway.enabled=false --set grafana-enabled=false --set prometheus.enabled=false --set global.disablePolicyChecks=true | kubectl apply -f -
```

**Comment by amarrella** [comment]
I think this is due to the helm version being `< 2.10`. Would it be possible to upgrade helm?

**Comment by KarstenSiemer** [comment]
i still experience this in version v0.12.0-rc3.
I have the prometheus operator and this registers the crds by itself. I cant be applied via argocd because of the dry run

**Comment by jessesuen** [comment]
@KarstenSiemer can you share the output of `argocd app get APPNAME -o yaml` after the failed sync? I would like to see the errors happening during the sync.
