### ISSUE TITLE
skipCrds not part of ApplicationSet CRD in 2.3.x

### ISSUE THREAD

**Issue by ebr** [argoproj/argo-cd#8432]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

https://github.com/argoproj/argo-cd/pull/8012 includes the new `skipCrds` key in the `Application` spec. However, this key is missing from the `ApplicationSet` spec.

**To Reproduce**

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app-set
spec:
  generators: []
  template:
    metadata:
      name: my-app-set-{{name}}
    spec:
      destination:
        namespace: default
        server: "{{server}}"
      project: default
      source:
        repoURL: "https://my-helm-chart-repo"
        chart: my-chart
        targetRevision: "^1.0"
        helm:
          valueFiles:
            - values.yaml
          skipCrds: true
```

```
$ kubectl apply -f my-app-set.yaml                           
error: error validating "my-app-set.yaml": error validating data: ValidationError(ApplicationSet.spec.template.spec.source.helm): unknown field "skipCrds" in io.argoproj.v1alpha1.ApplicationSet.spec.template.spec.source.helm; if you choose to ignore these errors, turn validation off with --validate=false
```

The `Application` resources can be modified directly to include this key, and that works without an issue because it is part of the `Application` CRD in 2.3.x

**Expected Behaviour**

The `ApplicationSet` manifest should be applied successfully, and its `Application` resources should be updated with the `skipCrds` flag.

**Version**

```shell
argocd: v2.3.0-rc5+aa54aa7
  BuildDate: 2022-02-05T00:45:42Z
  GitCommit: aa54aa7eda70f5e049c9e25df75221d899efff4b
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.3.0-rc5+aa54aa7
  BuildDate: 2022-02-04T23:39:21Z
  GitCommit: aa54aa7eda70f5e049c9e25df75221d899efff4b
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.7.2+g663a896
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Comment by alexmt** [comment]
This is fixed by https://github.com/argoproj/argo-cd/pull/8416 . Next RC will have changes

**Comment by alexmt** [comment]
Sorry, closed it incorrectly - the issue is still there

**Comment by jstewart612** [comment]
Anything happening here?

**Comment by alexmt** [comment]
Issue is fixed by https://github.com/argoproj/argo-cd/pull/8744

**Comment by davidblum** [comment]
Still seeing this error in argo-cd `v2.3.2`, deployed via helm chart `4.2.2`

```
error validating data: ValidationError(ApplicationSet.spec.template.spec.source.helm): unknown field "skipCrds" in io.argoproj.v1alpha1.ApplicationSet.spec.template.spec.source.helm
```
![image](https://user-images.githubusercontent.com/7356579/159811339-09771256-f58d-435f-9900-8ddb3b6b015f.png)


I'm using an application set to deploy the prometheus kube-stack.

```
❯ argocd version
argocd: v2.2.3+987f665.dirty
  BuildDate: 2022-01-20T02:00:16Z
  GitCommit: 987f6659b88e656a8f6f8feef87f4dd467d53c44
  GitTreeState: dirty
  GoVersion: go1.17.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.3.2+ecc2af9
  BuildDate: 2022-03-23T00:40:57Z
  GitCommit: ecc2af9dcaa12975e654cde8cbbeaffbb315f75c
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.0+gd141386
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0

```
Template example:
```
{{- range $index, $service :=  ((.Values.packageServices)) }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $service.name }}-appset
  labels:
    kubernetes.example.com/package: {{ $.Values.packageName }}
    kubernetes.example.com/package-version: {{ $.Values.packageVersion | quote }}
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            kubernetes.example.com/cluster-type: "mgmt"
            kubernetes.example.com/release-cycle: {{ $.Values.releaseChannel | default  "alpha"}}
  template: {{ $service.template | nindent 4 }}
---
{{- end }}
```
```
packageServices:
  - name: kube-prometheus-stack
    template: |
      metadata:
        name: kube-prometheus-stack
        namespace: argocd
      spec:
        destination:
          namespace: monitoring
          server: "https://kubernetes.default.svc"
        project: services-mgmt-core
        source:
          helm:
            skipCrds: true
          repoURL: "https://prometheus-community.github.io/helm-charts"
          chart: "kube-prometheus-stack"
          targetRevision: "34.0.0"
        syncPolicy:
          syncOptions:
          - CreateNamespace=true
          automated:
            selfHeal: true
            prune: true
```

**Comment by davidblum** [comment]
Update:

This is actually an issue with the `helm-argo` chart, it does not correctly update CRD's.  

To fix this, i had to manually delete the CRD, then reinstall the helm chart, and the latest CRD was created.

I'll link the issue once its created.

**Comment by PhotoTeeborChoka** [comment]
@davidblum what exactly did you delete?

**Comment by davidblum** [comment]
@PhotoTeeborChoka I deleted the Argo CRD related to application sets:

```
kubectl delete crd applicationsets.argoproj.io
``` 

You can get a full list of argo CRD's with:
```
kubectl get crd | grep -i argoproj
```

If you delete this CRD, you'll need to re-apply / re-sync the helm argo cd chart so it puts down the latest CRD.

I used this command to verify the CRD has the correct version for `skipCRD``

```
kubectl get crd applicationsets.argoproj.io -o yaml | grep -i skipcrd
```

You can also manually apply the _latest_ application set CRD:

```
curl https://raw.githubusercontent.com/argoproj/argo-helm/master/charts/argo-cd/crds/crd-applicationset.yaml | kubectl apply -f -
```

**Comment by PhotoTeeborChoka** [comment]
Thanks, that helped. Everything works now.

**Comment by ops-hummus** [comment]
@davidblum 
Are you sure it's working? I tried using skipCrds from an applicationset (deploying Prometheus if it matters), and it did generated an application, but eventually it didn’t include the skipscrd in the application cr. What am I missing?

**Comment by davidblum** [comment]
@ops-hummus The steps I outlined above worked for me.

What issue are you seeing?

Have you tried running the steps I suggest [here](https://github.com/argoproj/argo-cd/issues/8432#issuecomment-1139743726) ?

Can you post some logs or relevant configs?
