### ISSUE TITLE
grafana.apps.argoproj.io is unavailable

### ISSUE THREAD

**Issue by onstring** [argoproj/argo-cd#8781]
**Describe the bug**

The link for https://grafana.apps.argoproj.io/ on the following [document](https://argo-cd.readthedocs.io/en/stable/operator-manual/metrics/#dashboards) is unavailable.

**Comment by rishabh625** [comment]
@leoluz : grafana demo is not active, what can be done to get it running?or we remove it from docs?

**Comment by alexmt** [comment]
Demo instance is fixed now. Thank you for letting us know about the issue!

**Comment by sethyv** [comment]
The link is still not active:

https://grafana.apps.argoproj.io/
