### ISSUE TITLE
Application OutOfSync foverver. Manifest rendered by argocd does not match the apiserver's version

### ISSUE THREAD

**Issue by juliohm1978** [argoproj/argo-cd#8833]
**Describe the bug**
The application status never reaches **Synced**, it stays forever in **OutOfSync**.

Clicking the APP DIFF button shows that the differences between the rendered manifest and the apiserver response:

![image](https://user-images.githubusercontent.com/4145456/159188720-5e0d4b97-f1eb-45a7-9fba-05ce939f0f49.png)

In this case, the differences are apparently meaningless:

* cpu limits compared as '1' (string) and 1 (int)
* probe initialDelaySeconds compared as 0 and `(nothing)`.

How can I make this work? Any application configuration I can use to make argocd ignore those differences?

**Comment by juliohm1978** [comment]
One way to workaround the issue is to define `ignoreDifferences` in the application spec.

```yaml
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - .spec.template.spec.containers[].livenessProbe
        - .spec.template.spec.containers[].readinessProbe
        - .spec.template.spec.containers[].startupProbe
        - .spec.template.spec.containers[].resources
```

But I'm not sure this would be acceptable, because it prevents the application from updating these values via argocd.

**Comment by vijayqeguy** [comment]
@juliohm1978 what is your ArgoCD version?

**Comment by juliohm1978** [comment]
Using v2.3.3

**Comment by vijayqeguy** [comment]
we faced the same issue. looks like `default` values are not retained and hence it fails during DIFF. we fixed that by avoiding in our yaml, just to match the saved state.

in your case, 0 is the default value for `initialDelaySeconds`. `cpu` you might have to change it to string

**Comment by juliohm1978** [comment]
Yes, thank you!

I'm working around by just specifying custom values to the probes. It works fine in my case, but this is probably not acceptable for people who have to deal with helm charts that do now allow these values to be overriden.

**Comment by guitmz** [comment]
this is still an issue btw (v2.6.1), any official position regarding it?

**Comment by davekpatrick** [comment]
Using v2.4.16 and looking to upgrade to v2.6.x, any update on this issue, particularly for the string / int cases like the below

![Screenshot 2023-04-14 at 8 45 06 AM](https://user-images.githubusercontent.com/58055667/232047724-e4aafcd9-2de3-4b1c-af98-b0e9a1db6521.jpg)

**Comment by Rohlik** [comment]
Still broken, even in `v2.11.2+25f7504` 😞.

**Comment by cyrilico** [comment]
v2.12.1+26b2039, still an issue

**Comment by boldfield** [comment]
Having the same issue with v2.13.0-rc2+0f083c9

**Comment by skydontdribble** [comment]
Seeing issue in v2.13.0. Is this planned to be addressed?
![Screenshot 2024-11-30 at 1 02 08 PM](https://github.com/user-attachments/assets/cce095be-4e89-4f22-8123-6dfc7665ccb0)

**Comment by eduardbulai** [comment]
ArgoCD 3.0.6 here, problem persists. Years later. 😀
