### ISSUE TITLE
Secret data not redacted in last-applied-configuration

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#897]
If a user is managing a secret through git, then even though we redact the data payload, we do not redact the contents of last-applied-configuration.

**Comment by jessesuen** [comment]
Also, looking at the code, if the user is using `stringData` instead of `data` key, then it is also not redacted.

**Comment by jessesuen** [comment]
> Also, looking at the code, if the user is using stringData instead of data key, then it is also not redacted.

For the stringData, we have an existing helper which can normalize a secret by moving stringData keys, base64 encoding them into data. This should help with handling the stringData case, but for last-applied, we still need to do something.

**Comment by alexmt** [comment]
Fixed

**Comment by balchua** [comment]
I am still seeing the unredacted values in the last-applied-configuration.  We are using argocd v1.0.0.

**Comment by balchua** [comment]
Thanks for reopening the issue.

**Comment by alexmt** [comment]
Thank you for reporting the bug @balchua ! PR with the fix is in review: https://github.com/argoproj/argo-cd/pull/1920

**Comment by yiscasar** [comment]
Hi,
It seem like the issue still happens (argo version v2.6.1+3f143c9). If I run
`kubectl get secret mySecret -o yaml` or `kubectl describe secret mySecret` I still see the secret values as plain text in"kubectl.kubernetes.io/last-applied-configuration" annotation.
