### ISSUE TITLE
ArgoCD PROJECT UI link is 404 error when using "--rootpath"

### ISSUE THREAD

**Issue by reefland** [argoproj/argo-cd#9599]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

ArgoCD is deployed using `--rootpath=/argocd`.  ArgoCD overall works fine, however PROJECT link in the UI does not seem to be respecting the `rootpath`.

**To Reproduce**

* Select any ArgoCD application in the web UI.
* Click the root of the application to bring up the Summary screen.
* The link for the `PROJECT` such as `default` does not include the contents of `--rootpath=/argocd`
* Click the link and you get a 404 page not found.

The `Log out` button is also a incorrect in that it protocol switches from HTTPS to HTTP, as I do not have an automatic redirect this results in a 404.  There is no reason that ArgoCD should change protocol upon logout.

**Expected behavior**

The links in the UI should respect the contents of  `--rootpath=/argocd`

**Screenshots**

![argocd_url_issue](https://user-images.githubusercontent.com/16230914/172429835-06b5fb8f-f08b-4f44-963f-da478510da97.png)

**Version**

```shell
Not deploying the ArgoCD cli, UI shows: v2.3.4+ac8b7df
```

**Logs**

```
Paste any relevant application logs here.


```

**Comment by reefland** [comment]
@alexmt - I saw this was merged into master 17 days ago and there have been several releases since then.  I can't tell if this has been included in a release yet, but its still broken with `v2.4.6+a48bca0`.

**Comment by crenshaw-dev** [comment]
Thanks for the reminder @reefland! It'll be part of 2.4.7. I'm going to see if I can get a few more fixes merged and then cut a release in the next 3ish days.

**Comment by reefland** [comment]
The fix for the `rootpath` is working well.  However, the other issue from above:
```
The Log out button is also a incorrect in that it protocol switches from HTTPS to HTTP, as I do not have an automatic redirect this results in a 404. There is no reason that ArgoCD should change protocol upon logout.
```
Still not right.   Click Log Out I still get a 404 page not found because it is switching from HTTPS to HTTP.

**Comment by crenshaw-dev** [comment]
Re-opening to track the "log out" issue.
