### ISSUE TITLE
Save button should be visible even when scrolled down

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#9928]
# Summary

When one edits the app details pane, one regularly needs to scroll down to get to the setting to change. The save button should be accessible w/o having to scroll back up.

# Motivation

Normally `save` buttons are in toolbars at the top of windows that are not scrolled off screen when one scrolls their corresponding document.

# Proposal

Move the button out of the scrolling part of the document.

**Comment by ashutosh16** [comment]
I have added the scrollbar to the manifest view.  Does this improve user experience? 


![Screen Shot 2022-08-17 at 1 44 04 PM](https://user-images.githubusercontent.com/11219262/185248620-e3eaab4b-757e-4e99-8773-10d79a86c31c.png)
![Screen Shot 2022-08-17 at 1 44 17 PM](https://user-images.githubusercontent.com/11219262/185248606-6e98c060-2bfb-41eb-b719-5de1d0795187.png)

**Comment by ashutosh16** [comment]
@crenshaw-dev  This issue is fixed, can we close this issue?

**Comment by jsoref** [comment]
At least in v2.4.11+3d9e9f2 we're still seeing the top area scroll off.

Note that this image is not an example of a "fixed" state:
![scrolling the wrong scrollbar](https://user-images.githubusercontent.com/11219262/185480486-1d3e8c3d-d61c-4efc-a432-8e1654796ff8.gif)

the fact that it shows the scrollbar scrolled offscreen is an indication that it's broken. There's also an outer scrollbar, and the whole thing is quite a bit of a mess.

**Comment by crenshaw-dev** [comment]
@jsoref so your preference would be for the Save/Cancel buttons to be "sticky" - i.e. stick to the top of the screen when the _outer_ scrollbar scrolls down the editor.

I believe this is possible with recent CSS features (hopefully no JS necessary). @ashutosh16 would you be up for taking another crack at this?

**Comment by jsoref** [comment]
You can definitely do this w/ pure CSS.

The problem is that right now you have a whole bunch of overflowing-scrolling divs nested and the save button is inside one (or more) of them.

Note that the screenshot that was provided was for a *resource* whereas this bug's steps are for editing an `application` -- I've updated the summary to make it clearer.

Here's my sample application:
<img width="1538" alt="image" src="https://user-images.githubusercontent.com/2119212/190268131-86193c47-cb61-4e49-9752-2859208968cc.png">
And here's what happens when I scroll it:
<img width="1541" alt="image" src="https://user-images.githubusercontent.com/2119212/190268282-15eb4d91-d6a0-4d1b-8cc4-3e8dfeccd3ec.png">
